// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from zumo_core.djinni

#import "ZKAuthCallback+Private.h"
#import "ZKAuthCallback.h"
#import "DJICppWrapperCache+Private.h"
#import "DJIError.h"
#import "DJIMarshal+Private.h"
#import "DJIObjcWrapperCache+Private.h"
#import "ZKUser+Private.h"
#include <exception>
#include <stdexcept>
#include <utility>

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@interface ZKAuthCallbackCppProxy : NSObject<ZKAuthCallback>

- (id)initWithCpp:(const std::shared_ptr<::zumo::AuthCallback>&)cppRef;

@end

@implementation ZKAuthCallbackCppProxy {
    ::djinni::CppProxyCache::Handle<std::shared_ptr<::zumo::AuthCallback>> _cppRefHandle;
}

- (id)initWithCpp:(const std::shared_ptr<::zumo::AuthCallback>&)cppRef
{
    if (self = [super init]) {
        _cppRefHandle.assign(cppRef);
    }
    return self;
}

- (void)onError:(int16_t)errorCode
   errorMessage:(nonnull NSString *)errorMessage {
    try {
        _cppRefHandle.get()->on_error(::djinni::I16::toCpp(errorCode),
                                      ::djinni::String::toCpp(errorMessage));
    } DJINNI_TRANSLATE_EXCEPTIONS()
}

- (void)onSuccess:(nullable ZKUser *)user {
    try {
        _cppRefHandle.get()->on_success(::djinni_generated::User::toCpp(user));
    } DJINNI_TRANSLATE_EXCEPTIONS()
}

namespace djinni_generated {

class AuthCallback::ObjcProxy final
: public ::zumo::AuthCallback
, private ::djinni::ObjcProxyBase<ObjcType>
{
    friend class ::djinni_generated::AuthCallback;
public:
    using ObjcProxyBase::ObjcProxyBase;
    void on_error(int16_t c_error_code, const std::string & c_error_message) override
    {
        @autoreleasepool {
            [djinni_private_get_proxied_objc_object() onError:(::djinni::I16::fromCpp(c_error_code))
                                                 errorMessage:(::djinni::String::fromCpp(c_error_message))];
        }
    }
    void on_success(const std::shared_ptr<::zumo::User> & c_user) override
    {
        @autoreleasepool {
            [djinni_private_get_proxied_objc_object() onSuccess:(::djinni_generated::User::fromCpp(c_user))];
        }
    }
};

}  // namespace djinni_generated

namespace djinni_generated {

auto AuthCallback::toCpp(ObjcType objc) -> CppType
{
    if (!objc) {
        return nullptr;
    }
    if ([(id)objc isKindOfClass:[ZKAuthCallbackCppProxy class]]) {
        return ((ZKAuthCallbackCppProxy*)objc)->_cppRefHandle.get();
    }
    return ::djinni::get_objc_proxy<ObjcProxy>(objc);
}

auto AuthCallback::fromCppOpt(const CppOptType& cpp) -> ObjcType
{
    if (!cpp) {
        return nil;
    }
    if (auto cppPtr = dynamic_cast<ObjcProxy*>(cpp.get())) {
        return cppPtr->djinni_private_get_proxied_objc_object();
    }
    return ::djinni::get_cpp_proxy<ZKAuthCallbackCppProxy>(cpp);
}

}  // namespace djinni_generated

@end
