// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from zumo_core.djinni

#include "auth_callback.hpp"
#include <memory>

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@protocol ZKAuthCallback;

namespace djinni_generated {

class AuthCallback
{
public:
    using CppType = std::shared_ptr<::zumo::AuthCallback>;
    using CppOptType = std::shared_ptr<::zumo::AuthCallback>;
    using ObjcType = id<ZKAuthCallback>;

    using Boxed = AuthCallback;

    static CppType toCpp(ObjcType objc);
    static ObjcType fromCppOpt(const CppOptType& cpp);
    static ObjcType fromCpp(const CppType& cpp) { return fromCppOpt(cpp); }

private:
    class ObjcProxy;
};

}  // namespace djinni_generated

