// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from records.djinni

#import "ZKCard.h"
#include "card.hpp"

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@class ZKCard;

namespace djinni_generated {

struct Card
{
    using CppType = ::zumo::Card;
    using ObjcType = ZKCard*;

    using Boxed = Card;

    static CppType toCpp(ObjcType objc);
    static ObjcType fromCpp(const CppType& cpp);
};

}  // namespace djinni_generated
