// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from user.djinni

#include "card_details_callback.hpp"
#include <memory>

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@protocol ZKCardDetailsCallback;

namespace djinni_generated {

class CardDetailsCallback
{
public:
    using CppType = std::shared_ptr<::zumo::CardDetailsCallback>;
    using CppOptType = std::shared_ptr<::zumo::CardDetailsCallback>;
    using ObjcType = id<ZKCardDetailsCallback>;

    using Boxed = CardDetailsCallback;

    static CppType toCpp(ObjcType objc);
    static ObjcType fromCppOpt(const CppOptType& cpp);
    static ObjcType fromCpp(const CppType& cpp) { return fromCppOpt(cpp); }

private:
    class ObjcProxy;
};

}  // namespace djinni_generated

