// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from records.djinni

#import "ZKComposedExchange+Private.h"
#import "ZKAccount+Private.h"
#import "ZKQuote+Private.h"
#include <cassert>

namespace djinni_generated {

auto ComposedExchange::toCpp(ObjcType obj) -> CppType
{
    assert(obj);
    return {::djinni_generated::Account::toCpp(obj.debitAccount),
            ::djinni_generated::Account::toCpp(obj.creditAccount),
            ::djinni_generated::Quote::toCpp(obj.quote)};
}

auto ComposedExchange::fromCpp(const CppType& cpp) -> ObjcType
{
    return [[ZKComposedExchange alloc] initWithDebitAccount:(::djinni_generated::Account::fromCpp(cpp.debit_account))
                                              creditAccount:(::djinni_generated::Account::fromCpp(cpp.credit_account))
                                                      quote:(::djinni_generated::Quote::fromCpp(cpp.quote))];
}

}  // namespace djinni_generated
