// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from records.djinni

#import "ZKComposedExchange.h"
#include "composed_exchange.hpp"

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@class ZKComposedExchange;

namespace djinni_generated {

struct ComposedExchange
{
    using CppType = ::zumo::ComposedExchange;
    using ObjcType = ZKComposedExchange*;

    using Boxed = ComposedExchange;

    static CppType toCpp(ObjcType objc);
    static ObjcType fromCpp(const CppType& cpp);
};

}  // namespace djinni_generated
