// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from state.djinni

#import "ZKCryptoProperties.h"
#include "crypto_properties.hpp"

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@class ZKCryptoProperties;

namespace djinni_generated {

struct CryptoProperties
{
    using CppType = ::zumo::CryptoProperties;
    using ObjcType = ZKCryptoProperties*;

    using Boxed = CryptoProperties;

    static CppType toCpp(ObjcType objc);
    static ObjcType fromCpp(const CppType& cpp);
};

}  // namespace djinni_generated
