// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from enums.djinni

#import "ZKCustodyType.h"
#include "custody_type.hpp"

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@class ZKCustodyType;

namespace djinni_generated {

struct CustodyType
{
    using CppType = ::zumo::CustodyType;
    using ObjcType = ZKCustodyType*;

    using Boxed = CustodyType;

    static CppType toCpp(ObjcType objc);
    static ObjcType fromCpp(const CppType& cpp);
};

}  // namespace djinni_generated
