// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from enums.djinni

#import "ZKExchangeSide.h"
#include "exchange_side.hpp"

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@class ZKExchangeSide;

namespace djinni_generated {

struct ExchangeSide
{
    using CppType = ::zumo::ExchangeSide;
    using ObjcType = ZKExchangeSide*;

    using Boxed = ExchangeSide;

    static CppType toCpp(ObjcType objc);
    static ObjcType fromCpp(const CppType& cpp);
};

}  // namespace djinni_generated
