// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from state.djinni

#import "ZKExchange+Private.h"
#import "DJIMarshal+Private.h"
#import "ZKExchangeStatus+Private.h"
#include <cassert>

namespace djinni_generated {

auto Exchange::toCpp(ObjcType obj) -> CppType
{
    assert(obj);
    return {::djinni::String::toCpp(obj.id),
            ::djinni::Enum<::zumo::ExchangeStatus, ZKExchangeStatus>::toCpp(obj.status),
            ::djinni::String::toCpp(obj.depositCurrency),
            ::djinni::String::toCpp(obj.depositAccountId),
            ::djinni::String::toCpp(obj.depositTransactionId),
            ::djinni::String::toCpp(obj.withdrawCurrency),
            ::djinni::String::toCpp(obj.withdrawAccountId),
            ::djinni::Optional<std::experimental::optional, ::djinni::String>::toCpp(obj.withdrawTransactionId),
            ::djinni::String::toCpp(obj.amount),
            ::djinni::String::toCpp(obj.returnAmount),
            ::djinni::Optional<std::experimental::optional, ::djinni::I64>::toCpp(obj.submittedAt),
            ::djinni::Optional<std::experimental::optional, ::djinni::I64>::toCpp(obj.confirmedAt)};
}

auto Exchange::fromCpp(const CppType& cpp) -> ObjcType
{
    return [[ZKExchange alloc] initWithId:(::djinni::String::fromCpp(cpp.id))
                                   status:(::djinni::Enum<::zumo::ExchangeStatus, ZKExchangeStatus>::fromCpp(cpp.status))
                          depositCurrency:(::djinni::String::fromCpp(cpp.deposit_currency))
                         depositAccountId:(::djinni::String::fromCpp(cpp.deposit_account_id))
                     depositTransactionId:(::djinni::String::fromCpp(cpp.deposit_transaction_id))
                         withdrawCurrency:(::djinni::String::fromCpp(cpp.withdraw_currency))
                        withdrawAccountId:(::djinni::String::fromCpp(cpp.withdraw_account_id))
                    withdrawTransactionId:(::djinni::Optional<std::experimental::optional, ::djinni::String>::fromCpp(cpp.withdraw_transaction_id))
                                   amount:(::djinni::String::fromCpp(cpp.amount))
                             returnAmount:(::djinni::String::fromCpp(cpp.return_amount))
                              submittedAt:(::djinni::Optional<std::experimental::optional, ::djinni::I64>::fromCpp(cpp.submitted_at))
                              confirmedAt:(::djinni::Optional<std::experimental::optional, ::djinni::I64>::fromCpp(cpp.confirmed_at))];
}

}  // namespace djinni_generated
