// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from records.djinni

#import "ZKExchangeSetting.h"
#include "exchange_setting.hpp"

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@class ZKExchangeSetting;

namespace djinni_generated {

struct ExchangeSetting
{
    using CppType = ::zumo::ExchangeSetting;
    using ObjcType = ZKExchangeSetting*;

    using Boxed = ExchangeSetting;

    static CppType toCpp(ObjcType objc);
    static ObjcType fromCpp(const CppType& cpp);
};

}  // namespace djinni_generated
