// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from records.djinni

#import "ZKExchangeRate+Private.h"
#import "DJIMarshal+Private.h"
#import "NSDecimalNumber+ZumoKit.h"
#include <cassert>

namespace djinni_generated {

auto ExchangeRate::toCpp(ObjcType obj) -> CppType
{
    assert(obj);
    return {::djinni::String::toCpp(obj.id),
            ::djinni::String::toCpp(obj.depositCurrency),
            ::djinni::String::toCpp(obj.withdrawCurrency),
            ::zumo::djinni::objc::DecimalConverter::toCpp(obj.value),
            ::djinni::I64::toCpp(obj.validTo),
            ::djinni::I64::toCpp(obj.timestamp)};
}

auto ExchangeRate::fromCpp(const CppType& cpp) -> ObjcType
{
    return [[ZKExchangeRate alloc] initWithId:(::djinni::String::fromCpp(cpp.id))
                              depositCurrency:(::djinni::String::fromCpp(cpp.deposit_currency))
                             withdrawCurrency:(::djinni::String::fromCpp(cpp.withdraw_currency))
                                        value:(::zumo::djinni::objc::DecimalConverter::fromCpp(cpp.value))
                                      validTo:(::djinni::I64::fromCpp(cpp.valid_to))
                                    timestamp:(::djinni::I64::fromCpp(cpp.timestamp))];
}

}  // namespace djinni_generated
