// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from state.djinni

#import "ZKFiatProperties+Private.h"
#import "DJIMarshal+Private.h"
#include <cassert>

namespace djinni_generated {

auto FiatProperties::toCpp(ObjcType obj) -> CppType
{
    assert(obj);
    return {::djinni::Optional<std::experimental::optional, ::djinni::String>::toCpp(obj.accountNumber),
            ::djinni::Optional<std::experimental::optional, ::djinni::String>::toCpp(obj.sortCode),
            ::djinni::Optional<std::experimental::optional, ::djinni::String>::toCpp(obj.bic),
            ::djinni::Optional<std::experimental::optional, ::djinni::String>::toCpp(obj.iban)};
}

auto FiatProperties::fromCpp(const CppType& cpp) -> ObjcType
{
    return [[ZKFiatProperties alloc] initWithAccountNumber:(::djinni::Optional<std::experimental::optional, ::djinni::String>::fromCpp(cpp.account_number))
                                                  sortCode:(::djinni::Optional<std::experimental::optional, ::djinni::String>::fromCpp(cpp.sort_code))
                                                       bic:(::djinni::Optional<std::experimental::optional, ::djinni::String>::fromCpp(cpp.bic))
                                                      iban:(::djinni::Optional<std::experimental::optional, ::djinni::String>::fromCpp(cpp.iban))];
}

}  // namespace djinni_generated
