// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from networking.djinni

#include "http_provider.hpp"
#include <memory>

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@protocol ZKHttpProvider;

namespace djinni_generated {

class HttpProvider
{
public:
    using CppType = std::shared_ptr<::zumo::HttpProvider>;
    using CppOptType = std::shared_ptr<::zumo::HttpProvider>;
    using ObjcType = id<ZKHttpProvider>;

    using Boxed = HttpProvider;

    static CppType toCpp(ObjcType objc);
    static ObjcType fromCppOpt(const CppOptType& cpp);
    static ObjcType fromCpp(const CppType& cpp) { return fromCppOpt(cpp); }

private:
    class ObjcProxy;
};

}  // namespace djinni_generated

