// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from enums.djinni

#import "ZKLogLevel.h"
#include "log_level.hpp"

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@class ZKLogLevel;

namespace djinni_generated {

struct LogLevel
{
    using CppType = ::zumo::LogLevel;
    using ObjcType = ZKLogLevel*;

    using Boxed = LogLevel;

    static CppType toCpp(ObjcType objc);
    static ObjcType fromCpp(const CppType& cpp);
};

}  // namespace djinni_generated
