// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from records.djinni

#import "ZKQuote+Private.h"
#import "DJIMarshal+Private.h"
#import "NSDecimalNumber+ZumoKit.h"
#include <cassert>

namespace djinni_generated {

auto Quote::toCpp(ObjcType obj) -> CppType
{
    assert(obj);
    return {::djinni::String::toCpp(obj.id),
            ::djinni::I32::toCpp(obj.ttl),
            ::djinni::String::toCpp(obj.createdAt),
            ::djinni::String::toCpp(obj.expiresAt),
            ::djinni::String::toCpp(obj.debitCurrency),
            ::djinni::String::toCpp(obj.creditCurrency),
            ::zumo::djinni::objc::DecimalConverter::toCpp(obj.price),
            ::zumo::djinni::objc::DecimalConverter::toCpp(obj.feeRate),
            ::zumo::djinni::objc::DecimalConverter::toCpp(obj.debitAmount),
            ::zumo::djinni::objc::DecimalConverter::toCpp(obj.feeAmount),
            ::zumo::djinni::objc::DecimalConverter::toCpp(obj.creditAmount)};
}

auto Quote::fromCpp(const CppType& cpp) -> ObjcType
{
    return [[ZKQuote alloc] initWithId:(::djinni::String::fromCpp(cpp.id))
                                   ttl:(::djinni::I32::fromCpp(cpp.ttl))
                             createdAt:(::djinni::String::fromCpp(cpp.created_at))
                             expiresAt:(::djinni::String::fromCpp(cpp.expires_at))
                         debitCurrency:(::djinni::String::fromCpp(cpp.debit_currency))
                        creditCurrency:(::djinni::String::fromCpp(cpp.credit_currency))
                                 price:(::zumo::djinni::objc::DecimalConverter::fromCpp(cpp.price))
                               feeRate:(::zumo::djinni::objc::DecimalConverter::fromCpp(cpp.fee_rate))
                           debitAmount:(::zumo::djinni::objc::DecimalConverter::fromCpp(cpp.debit_amount))
                             feeAmount:(::zumo::djinni::objc::DecimalConverter::fromCpp(cpp.fee_amount))
                          creditAmount:(::zumo::djinni::objc::DecimalConverter::fromCpp(cpp.credit_amount))];
}

}  // namespace djinni_generated
