// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from user.djinni

#include "stringified_json_callback.hpp"
#include <memory>

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@protocol ZKStringifiedJsonCallback;

namespace djinni_generated {

class StringifiedJsonCallback
{
public:
    using CppType = std::shared_ptr<::zumo::StringifiedJsonCallback>;
    using CppOptType = std::shared_ptr<::zumo::StringifiedJsonCallback>;
    using ObjcType = id<ZKStringifiedJsonCallback>;

    using Boxed = StringifiedJsonCallback;

    static CppType toCpp(ObjcType objc);
    static ObjcType fromCppOpt(const CppOptType& cpp);
    static ObjcType fromCpp(const CppType& cpp) { return fromCppOpt(cpp); }

private:
    class ObjcProxy;
};

}  // namespace djinni_generated

