// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from zumo_core.djinni

#import "ZKStateListener+Private.h"
#import "ZKStateListener.h"
#import "DJICppWrapperCache+Private.h"
#import "DJIError.h"
#import "DJIObjcWrapperCache+Private.h"
#import "ZKState+Private.h"
#include <exception>
#include <stdexcept>
#include <utility>

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@interface ZKStateListenerCppProxy : NSObject<ZKStateListener>

- (id)initWithCpp:(const std::shared_ptr<::zumo::StateListener>&)cppRef;

@end

@implementation ZKStateListenerCppProxy {
    ::djinni::CppProxyCache::Handle<std::shared_ptr<::zumo::StateListener>> _cppRefHandle;
}

- (id)initWithCpp:(const std::shared_ptr<::zumo::StateListener>&)cppRef
{
    if (self = [super init]) {
        _cppRefHandle.assign(cppRef);
    }
    return self;
}

- (void)update:(nonnull ZKState *)state {
    try {
        _cppRefHandle.get()->update(::djinni_generated::State::toCpp(state));
    } DJINNI_TRANSLATE_EXCEPTIONS()
}

namespace djinni_generated {

class StateListener::ObjcProxy final
: public ::zumo::StateListener
, private ::djinni::ObjcProxyBase<ObjcType>
{
    friend class ::djinni_generated::StateListener;
public:
    using ObjcProxyBase::ObjcProxyBase;
    void update(const ::zumo::State & c_state) override
    {
        @autoreleasepool {
            [djinni_private_get_proxied_objc_object() update:(::djinni_generated::State::fromCpp(c_state))];
        }
    }
};

}  // namespace djinni_generated

namespace djinni_generated {

auto StateListener::toCpp(ObjcType objc) -> CppType
{
    if (!objc) {
        return nullptr;
    }
    if ([(id)objc isKindOfClass:[ZKStateListenerCppProxy class]]) {
        return ((ZKStateListenerCppProxy*)objc)->_cppRefHandle.get();
    }
    return ::djinni::get_objc_proxy<ObjcProxy>(objc);
}

auto StateListener::fromCppOpt(const CppOptType& cpp) -> ObjcType
{
    if (!cpp) {
        return nil;
    }
    if (auto cppPtr = dynamic_cast<ObjcProxy*>(cpp.get())) {
        return cppPtr->djinni_private_get_proxied_objc_object();
    }
    return ::djinni::get_cpp_proxy<ZKStateListenerCppProxy>(cpp);
}

}  // namespace djinni_generated

@end
