// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from user.djinni

#include "submit_transaction_callback.hpp"
#include <memory>

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@protocol ZKSubmitTransactionCallback;

namespace djinni_generated {

class SubmitTransactionCallback
{
public:
    using CppType = std::shared_ptr<::zumo::SubmitTransactionCallback>;
    using CppOptType = std::shared_ptr<::zumo::SubmitTransactionCallback>;
    using ObjcType = id<ZKSubmitTransactionCallback>;

    using Boxed = SubmitTransactionCallback;

    static CppType toCpp(ObjcType objc);
    static ObjcType fromCppOpt(const CppOptType& cpp);
    static ObjcType fromCpp(const CppType& cpp) { return fromCppOpt(cpp); }

private:
    class ObjcProxy;
};

}  // namespace djinni_generated

