// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from state.djinni

#import "ZKTransactionCryptoProperties+Private.h"
#import "DJIMarshal+Private.h"
#include <cassert>

namespace djinni_generated {

auto TransactionCryptoProperties::toCpp(ObjcType obj) -> CppType
{
    assert(obj);
    return {::djinni::Optional<std::experimental::optional, ::djinni::String>::toCpp(obj.txHash),
            ::djinni::Optional<std::experimental::optional, ::djinni::I64>::toCpp(obj.nonce),
            ::djinni::String::toCpp(obj.fromAddress),
            ::djinni::Optional<std::experimental::optional, ::djinni::String>::toCpp(obj.toAddress),
            ::djinni::Optional<std::experimental::optional, ::djinni::String>::toCpp(obj.data),
            ::djinni::Optional<std::experimental::optional, ::djinni::String>::toCpp(obj.gasPrice),
            ::djinni::Optional<std::experimental::optional, ::djinni::String>::toCpp(obj.gasLimit),
            ::djinni::Map<::djinni::String, ::djinni::String>::toCpp(obj.fiatAmount),
            ::djinni::Map<::djinni::String, ::djinni::String>::toCpp(obj.fiatFee)};
}

auto TransactionCryptoProperties::fromCpp(const CppType& cpp) -> ObjcType
{
    return [[ZKTransactionCryptoProperties alloc] initWithTxHash:(::djinni::Optional<std::experimental::optional, ::djinni::String>::fromCpp(cpp.tx_hash))
                                                           nonce:(::djinni::Optional<std::experimental::optional, ::djinni::I64>::fromCpp(cpp.nonce))
                                                     fromAddress:(::djinni::String::fromCpp(cpp.from_address))
                                                       toAddress:(::djinni::Optional<std::experimental::optional, ::djinni::String>::fromCpp(cpp.to_address))
                                                            data:(::djinni::Optional<std::experimental::optional, ::djinni::String>::fromCpp(cpp.data))
                                                        gasPrice:(::djinni::Optional<std::experimental::optional, ::djinni::String>::fromCpp(cpp.gas_price))
                                                        gasLimit:(::djinni::Optional<std::experimental::optional, ::djinni::String>::fromCpp(cpp.gas_limit))
                                                      fiatAmount:(::djinni::Map<::djinni::String, ::djinni::String>::fromCpp(cpp.fiat_amount))
                                                         fiatFee:(::djinni::Map<::djinni::String, ::djinni::String>::fromCpp(cpp.fiat_fee))];
}

}  // namespace djinni_generated
