// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from state.djinni

#import "ZKTransactionFiatProperties.h"
#include "transaction_fiat_properties.hpp"

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@class ZKTransactionFiatProperties;

namespace djinni_generated {

struct TransactionFiatProperties
{
    using CppType = ::zumo::TransactionFiatProperties;
    using ObjcType = ZKTransactionFiatProperties*;

    using Boxed = TransactionFiatProperties;

    static CppType toCpp(ObjcType objc);
    static ObjcType fromCpp(const CppType& cpp);
};

}  // namespace djinni_generated
