// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from records.djinni

#import "ZKTransactionAmount+Private.h"
#import "DJIMarshal+Private.h"
#import "NSDecimalNumber+ZumoKit.h"
#include <cassert>

namespace djinni_generated {

auto TransactionAmount::toCpp(ObjcType obj) -> CppType
{
    assert(obj);
    return {::djinni::String::toCpp(obj.direction),
            ::djinni::Optional<std::optional, ::djinni::String>::toCpp(obj.userId),
            ::djinni::Optional<std::optional, ::djinni::String>::toCpp(obj.userIntegratorId),
            ::djinni::Optional<std::optional, ::djinni::String>::toCpp(obj.accountId),
            ::djinni::Optional<std::optional, ::zumo::djinni::objc::DecimalConverter>::toCpp(obj.amount),
            ::djinni::Optional<std::optional, ::djinni::Map<::djinni::String, ::djinni::F64>>::toCpp(obj.fiatAmount),
            ::djinni::Optional<std::optional, ::djinni::String>::toCpp(obj.address),
            ::djinni::Bool::toCpp(obj.isChange),
            ::djinni::Optional<std::optional, ::djinni::String>::toCpp(obj.accountNumber),
            ::djinni::Optional<std::optional, ::djinni::String>::toCpp(obj.sortCode),
            ::djinni::Optional<std::optional, ::djinni::String>::toCpp(obj.bic),
            ::djinni::Optional<std::optional, ::djinni::String>::toCpp(obj.iban)};
}

auto TransactionAmount::fromCpp(const CppType& cpp) -> ObjcType
{
    return [[ZKTransactionAmount alloc] initWithDirection:(::djinni::String::fromCpp(cpp.direction))
                                                   userId:(::djinni::Optional<std::optional, ::djinni::String>::fromCpp(cpp.user_id))
                                         userIntegratorId:(::djinni::Optional<std::optional, ::djinni::String>::fromCpp(cpp.user_integrator_id))
                                                accountId:(::djinni::Optional<std::optional, ::djinni::String>::fromCpp(cpp.account_id))
                                                   amount:(::djinni::Optional<std::optional, ::zumo::djinni::objc::DecimalConverter>::fromCpp(cpp.amount))
                                               fiatAmount:(::djinni::Optional<std::optional, ::djinni::Map<::djinni::String, ::djinni::F64>>::fromCpp(cpp.fiat_amount))
                                                  address:(::djinni::Optional<std::optional, ::djinni::String>::fromCpp(cpp.address))
                                                 isChange:(::djinni::Bool::fromCpp(cpp.is_change))
                                            accountNumber:(::djinni::Optional<std::optional, ::djinni::String>::fromCpp(cpp.account_number))
                                                 sortCode:(::djinni::Optional<std::optional, ::djinni::String>::fromCpp(cpp.sort_code))
                                                      bic:(::djinni::Optional<std::optional, ::djinni::String>::fromCpp(cpp.bic))
                                                     iban:(::djinni::Optional<std::optional, ::djinni::String>::fromCpp(cpp.iban))];
}

}  // namespace djinni_generated
