// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from records.djinni

#import "ZKTransactionFeeRate.h"
#include "transaction_fee_rate.hpp"

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@class ZKTransactionFeeRate;

namespace djinni_generated {

struct TransactionFeeRate
{
    using CppType = ::zumo::TransactionFeeRate;
    using ObjcType = ZKTransactionFeeRate*;

    using Boxed = TransactionFeeRate;

    static CppType toCpp(ObjcType objc);
    static ObjcType fromCpp(const CppType& cpp);
};

}  // namespace djinni_generated
