// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from records.djinni

#import "ZKTransactionAmount.h"
#include "transaction_amount.hpp"

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@class ZKTransactionAmount;

namespace djinni_generated {

struct TransactionAmount
{
    using CppType = ::zumo::TransactionAmount;
    using ObjcType = ZKTransactionAmount*;

    using Boxed = TransactionAmount;

    static CppType toCpp(ObjcType objc);
    static ObjcType fromCpp(const CppType& cpp);
};

}  // namespace djinni_generated
