// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from state.djinni

#import "ZKTransaction+Private.h"
#import "DJIMarshal+Private.h"
#import "ZKCryptoDetails+Private.h"
#include <cassert>

namespace djinni_generated {

auto Transaction::toCpp(ObjcType obj) -> CppType
{
    assert(obj);
    return {::djinni::String::toCpp(obj.id),
            ::djinni::String::toCpp(obj.type),
            ::djinni::String::toCpp(obj.accountId),
            ::djinni::String::toCpp(obj.currencyCode),
            ::djinni::Optional<std::experimental::optional, ::djinni::String>::toCpp(obj.fromUserId),
            ::djinni::Optional<std::experimental::optional, ::djinni::String>::toCpp(obj.toUserId),
            ::djinni::String::toCpp(obj.network),
            ::djinni::String::toCpp(obj.direction),
            ::djinni::String::toCpp(obj.status),
            ::djinni::Optional<std::experimental::optional, ::djinni::String>::toCpp(obj.amount),
            ::djinni::Optional<std::experimental::optional, ::djinni::String>::toCpp(obj.fee),
            ::djinni::Optional<std::experimental::optional, ::djinni_generated::CryptoDetails>::toCpp(obj.cryptoDetails),
            ::djinni::Optional<std::experimental::optional, ::djinni::String>::toCpp(obj.fiatDetails),
            ::djinni::Optional<std::experimental::optional, ::djinni::I64>::toCpp(obj.submittedAt),
            ::djinni::Optional<std::experimental::optional, ::djinni::I64>::toCpp(obj.confirmedAt),
            ::djinni::I64::toCpp(obj.timestamp)};
}

auto Transaction::fromCpp(const CppType& cpp) -> ObjcType
{
    return [[ZKTransaction alloc] initWithId:(::djinni::String::fromCpp(cpp.id))
                                        type:(::djinni::String::fromCpp(cpp.type))
                                   accountId:(::djinni::String::fromCpp(cpp.account_id))
                                currencyCode:(::djinni::String::fromCpp(cpp.currency_code))
                                  fromUserId:(::djinni::Optional<std::experimental::optional, ::djinni::String>::fromCpp(cpp.from_user_id))
                                    toUserId:(::djinni::Optional<std::experimental::optional, ::djinni::String>::fromCpp(cpp.to_user_id))
                                     network:(::djinni::String::fromCpp(cpp.network))
                                   direction:(::djinni::String::fromCpp(cpp.direction))
                                      status:(::djinni::String::fromCpp(cpp.status))
                                      amount:(::djinni::Optional<std::experimental::optional, ::djinni::String>::fromCpp(cpp.amount))
                                         fee:(::djinni::Optional<std::experimental::optional, ::djinni::String>::fromCpp(cpp.fee))
                               cryptoDetails:(::djinni::Optional<std::experimental::optional, ::djinni_generated::CryptoDetails>::fromCpp(cpp.crypto_details))
                                 fiatDetails:(::djinni::Optional<std::experimental::optional, ::djinni::String>::fromCpp(cpp.fiat_details))
                                 submittedAt:(::djinni::Optional<std::experimental::optional, ::djinni::I64>::fromCpp(cpp.submitted_at))
                                 confirmedAt:(::djinni::Optional<std::experimental::optional, ::djinni::I64>::fromCpp(cpp.confirmed_at))
                                   timestamp:(::djinni::I64::fromCpp(cpp.timestamp))];
}

}  // namespace djinni_generated
