// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from user.djinni

#include "user_listener.hpp"
#include <memory>

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@protocol ZKUserListener;

namespace djinni_generated {

class UserListener
{
public:
    using CppType = std::shared_ptr<::zumo::UserListener>;
    using CppOptType = std::shared_ptr<::zumo::UserListener>;
    using ObjcType = id<ZKUserListener>;

    using Boxed = UserListener;

    static CppType toCpp(ObjcType objc);
    static ObjcType fromCppOpt(const CppOptType& cpp);
    static ObjcType fromCpp(const CppType& cpp) { return fromCppOpt(cpp); }

private:
    class ObjcProxy;
};

}  // namespace djinni_generated

