// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from wallet.djinni

#include "wallet.hpp"
#include <memory>

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@class ZKWallet;

namespace djinni_generated {

class Wallet
{
public:
    using CppType = std::shared_ptr<::zumo::Wallet>;
    using CppOptType = std::shared_ptr<::zumo::Wallet>;
    using ObjcType = ZKWallet*;

    using Boxed = Wallet;

    static CppType toCpp(ObjcType objc);
    static ObjcType fromCppOpt(const CppOptType& cpp);
    static ObjcType fromCpp(const CppType& cpp) { return fromCppOpt(cpp); }

private:
    class ObjcProxy;
};

}  // namespace djinni_generated

