// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from networking.djinni

#import "ZKWebSocketFactory+Private.h"
#import "ZKWebSocketFactory.h"
#import "DJICppWrapperCache+Private.h"
#import "DJIError.h"
#import "DJIMarshal+Private.h"
#import "DJIObjcWrapperCache+Private.h"
#import "ZKWebSocket+Private.h"
#include <exception>
#include <stdexcept>
#include <utility>

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@interface ZKWebSocketFactoryCppProxy : NSObject<ZKWebSocketFactory>

- (id)initWithCpp:(const std::shared_ptr<::zumo::WebSocketFactory>&)cppRef;

@end

@implementation ZKWebSocketFactoryCppProxy {
    ::djinni::CppProxyCache::Handle<std::shared_ptr<::zumo::WebSocketFactory>> _cppRefHandle;
}

- (id)initWithCpp:(const std::shared_ptr<::zumo::WebSocketFactory>&)cppRef
{
    if (self = [super init]) {
        _cppRefHandle.assign(cppRef);
    }
    return self;
}

- (nullable id<ZKWebSocket>)createWebSocket:(nonnull NSString *)url {
    try {
        auto objcpp_result_ = _cppRefHandle.get()->create_web_socket(::djinni::String::toCpp(url));
        return ::djinni_generated::WebSocket::fromCpp(objcpp_result_);
    } DJINNI_TRANSLATE_EXCEPTIONS()
}

namespace djinni_generated {

class WebSocketFactory::ObjcProxy final
: public ::zumo::WebSocketFactory
, private ::djinni::ObjcProxyBase<ObjcType>
{
    friend class ::djinni_generated::WebSocketFactory;
public:
    using ObjcProxyBase::ObjcProxyBase;
    std::shared_ptr<::zumo::WebSocket> create_web_socket(const std::string & c_url) override
    {
        @autoreleasepool {
            auto objcpp_result_ = [djinni_private_get_proxied_objc_object() createWebSocket:(::djinni::String::fromCpp(c_url))];
            return ::djinni_generated::WebSocket::toCpp(objcpp_result_);
        }
    }
};

}  // namespace djinni_generated

namespace djinni_generated {

auto WebSocketFactory::toCpp(ObjcType objc) -> CppType
{
    if (!objc) {
        return nullptr;
    }
    if ([(id)objc isKindOfClass:[ZKWebSocketFactoryCppProxy class]]) {
        return ((ZKWebSocketFactoryCppProxy*)objc)->_cppRefHandle.get();
    }
    return ::djinni::get_objc_proxy<ObjcProxy>(objc);
}

auto WebSocketFactory::fromCppOpt(const CppOptType& cpp) -> ObjcType
{
    if (!cpp) {
        return nil;
    }
    if (auto cppPtr = dynamic_cast<ObjcProxy*>(cpp.get())) {
        return cppPtr->djinni_private_get_proxied_objc_object();
    }
    return ::djinni::get_cpp_proxy<ZKWebSocketFactoryCppProxy>(cpp);
}

}  // namespace djinni_generated

@end
