// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from networking.djinni

#include "web_socket.hpp"
#include <memory>

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@protocol ZKWebSocket;

namespace djinni_generated {

class WebSocket
{
public:
    using CppType = std::shared_ptr<::zumo::WebSocket>;
    using CppOptType = std::shared_ptr<::zumo::WebSocket>;
    using ObjcType = id<ZKWebSocket>;

    using Boxed = WebSocket;

    static CppType toCpp(ObjcType objc);
    static ObjcType fromCppOpt(const CppOptType& cpp);
    static ObjcType fromCpp(const CppType& cpp) { return fromCppOpt(cpp); }

private:
    class ObjcProxy;
};

}  // namespace djinni_generated

