// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from errors.djinni

#import "ZKZumoKitErrorCode+Private.h"
#import "DJIMarshal+Private.h"
#include <cassert>

namespace djinni_generated {

auto ZumoKitErrorCode::toCpp(ObjcType obj) -> CppType
{
    assert(obj);
    (void)obj; // Suppress warnings in relase builds for empty records
    return {};
}

auto ZumoKitErrorCode::fromCpp(const CppType& cpp) -> ObjcType
{
    (void)cpp; // Suppress warnings in relase builds for empty records
    return [[ZKZumoKitErrorCode alloc] init];
}

}  // namespace djinni_generated
