// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from errors.djinni

#import "ZKZumoKitErrorType+Private.h"
#import "DJIMarshal+Private.h"
#include <cassert>

namespace djinni_generated {

auto ZumoKitErrorType::toCpp(ObjcType obj) -> CppType
{
    assert(obj);
    (void)obj; // Suppress warnings in relase builds for empty records
    return {};
}

auto ZumoKitErrorType::fromCpp(const CppType& cpp) -> ObjcType
{
    (void)cpp; // Suppress warnings in relase builds for empty records
    return [[ZKZumoKitErrorType alloc] init];
}

}  // namespace djinni_generated
