// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from state.djinni

#pragma once

#include "stdx/optional.hpp"
#include <cstdint>
#include <string>
#include <utility>

namespace zumo {

/**
 * Account's crypto related properties.
 * @see account
 */
struct AccountCryptoProperties final {
    /** Account crypto address. */
    std::string address;
    /** Hierarchical Deterministic (HD) account derivation path. */
    std::string path;
    /** Ethereum account nonce if greater than 0 or null otherwise. */
    std::experimental::optional<int64_t> nonce;
    std::experimental::optional<std::string> utxo_pool;
    int8_t version;

    friend bool operator==(const AccountCryptoProperties& lhs, const AccountCryptoProperties& rhs);
    friend bool operator!=(const AccountCryptoProperties& lhs, const AccountCryptoProperties& rhs);

    AccountCryptoProperties(std::string address_,
                            std::string path_,
                            std::experimental::optional<int64_t> nonce_,
                            std::experimental::optional<std::string> utxo_pool_,
                            int8_t version_)
    : address(std::move(address_))
    , path(std::move(path_))
    , nonce(std::move(nonce_))
    , utxo_pool(std::move(utxo_pool_))
    , version(std::move(version_))
    {}
};

}  // namespace zumo
