// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from state.djinni

#pragma once

#include "account_type.hpp"
#include "network_type.hpp"
#include "stdx/optional.hpp"
#include <cstdint>
#include <string>
#include <utility>

namespace zumo {

struct Account final {
    std::string id;
    std::string path;
    std::string symbol;
    std::string coin;
    std::string address;
    std::string balance;
    std::experimental::optional<int64_t> nonce;
    NetworkType network;
    AccountType type;
    std::experimental::optional<std::string> utxo_pool;
    int8_t version;

    friend bool operator==(const Account& lhs, const Account& rhs);
    friend bool operator!=(const Account& lhs, const Account& rhs);

    Account(std::string id_,
            std::string path_,
            std::string symbol_,
            std::string coin_,
            std::string address_,
            std::string balance_,
            std::experimental::optional<int64_t> nonce_,
            NetworkType network_,
            AccountType type_,
            std::experimental::optional<std::string> utxo_pool_,
            int8_t version_)
    : id(std::move(id_))
    , path(std::move(path_))
    , symbol(std::move(symbol_))
    , coin(std::move(coin_))
    , address(std::move(address_))
    , balance(std::move(balance_))
    , nonce(std::move(nonce_))
    , network(std::move(network_))
    , type(std::move(type_))
    , utxo_pool(std::move(utxo_pool_))
    , version(std::move(version_))
    {}
};

}  // namespace zumo
