// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from state.djinni

#pragma once

#include <string>
#include <utility>

namespace zumo {

/** Account type. Only relevant for Bitcoin accounts. All other accounts are STANDARD account type. */
struct AccountType final {

    static std::string const STANDARD;

    static std::string const COMPATIBILITY;

    static std::string const SEGWIT;
};

}  // namespace zumo
