// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from records.djinni

#pragma once

#include <optional>
#include <string>
#include <utility>

namespace zumo {

/** Record describing user address details */
struct Address final {
    /** House number. */
    std::string house_number;
    /** First line of address. */
    std::string address_line_1;
    /** Second line of address or null. */
    std::optional<std::string> address_line_2;
    /** Country code in ISO 3166-1 Alpha-2 format, e.g. 'GB'. */
    std::string country;
    /** Post code. */
    std::string post_code;
    /** Post town */
    std::string post_town;

    friend bool operator==(const Address& lhs, const Address& rhs);
    friend bool operator!=(const Address& lhs, const Address& rhs);

    Address(std::string house_number_,
            std::string address_line_1_,
            std::optional<std::string> address_line_2_,
            std::string country_,
            std::string post_code_,
            std::string post_town_)
    : house_number(std::move(house_number_))
    , address_line_1(std::move(address_line_1_))
    , address_line_2(std::move(address_line_2_))
    , country(std::move(country_))
    , post_code(std::move(post_code_))
    , post_town(std::move(post_town_))
    {}
};

}  // namespace zumo
