// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from zumo_core.djinni

#pragma once

#include <cstdint>
#include <memory>
#include <string>

namespace zumo {

class User;

class AuthCallback {
public:
    virtual ~AuthCallback() {}

    virtual void on_error(int16_t error_code, const std::string & error_message) = 0;

    virtual void on_success(const std::shared_ptr<User> & user) = 0;
};

}  // namespace zumo
