// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from zumo_core.djinni

#pragma once

#include <memory>

namespace zumo {

class User;
struct ZumoKitError;

class AuthCallback {
public:
    virtual ~AuthCallback() {}

    virtual void on_error(const ZumoKitError & error) = 0;

    virtual void on_success(const std::shared_ptr<User> & user) = 0;
};

}  // namespace zumo
