// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from enums.djinni

#pragma once

#include <string>
#include <utility>

namespace zumo {

/** Card type, 'VIRTUAL' or 'PHYSICAL'. */
struct CardType final {

    static std::string const VIRTUAL;

    static std::string const PHYSICAL;
};

}  // namespace zumo
