// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from user.djinni

#pragma once

#include "exceptions.hpp"

namespace zumo {

struct CardDetails;

/** Callback interface used by methods in User class. */
class CardDetailsCallback {
public:
    virtual ~CardDetailsCallback() {}

    virtual void on_error(const ::zumo::ZumoKitException & e) = 0;

    virtual void on_success(const CardDetails & card_details) = 0;
};

}  // namespace zumo
