// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from records.djinni

#pragma once

#include <string>
#include <utility>

namespace zumo {

/** Record containing sensitive card details. */
struct CardDetails final {
    /** Card PAN, e.g 4564 6545 7997 5454. */
    std::string pan;
    /** Card CVV2, e.g. 078. */
    std::string cvv2;

    friend bool operator==(const CardDetails& lhs, const CardDetails& rhs);
    friend bool operator!=(const CardDetails& lhs, const CardDetails& rhs);

    CardDetails(std::string pan_,
                std::string cvv2_)
    : pan(std::move(pan_))
    , cvv2(std::move(cvv2_))
    {}
};

}  // namespace zumo
