// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from state.djinni

#pragma once

#include <string>
#include <utility>

namespace zumo {

/** Curency type, 'FIAT' or 'CRYPTO'. */
struct CurrencyType final {

    static std::string const FIAT;

    static std::string const CRYPTO;
};

}  // namespace zumo
