// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from state.djinni

#pragma once

#include <string>
#include <utility>

namespace zumo {

struct ExchangeStatus final {

    static std::string const PENDING;

    static std::string const DEPOSITED;

    static std::string const CONFIRMED;

    static std::string const FAILED;

    static std::string const RESUBMITTED;

    static std::string const CANCELLED;

    static std::string const PAUSED;
};

}  // namespace zumo
