// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from enums.djinni

#pragma once

#include <string>
#include <utility>

namespace zumo {

/** Exchange side, 'BUY' or 'SELL'. */
struct ExchangeSide final {

    static std::string const BUY;

    static std::string const SELL;
};

}  // namespace zumo
