// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from records.djinni

#pragma once

#include "zumo/decimal.hpp"
#include <cstdint>
#include <string>
#include <utility>

namespace zumo {

/**
 * Record containing Zumo exchange rates used in making exchanges.
 * Can also be used to display amounts in local currency to the user.
 */
struct ExchangeRate final {
    /** Identifier. */
    std::string id;
    /**
     * Currency from which exchange is being made.
     * @see CurrencyCode
     */
    std::string from_currency;
    /**
     * Currency from which exchange is being made.
     * @see CurrencyCode
     */
    std::string to_currency;
    /** Value of 1 unit of deposit currency in target currency. */
    ::zumo::Decimal value;
    /** Epoch timestamp representing expiration time of this exchange rate. */
    int64_t valid_to;
    /** Epoch timestamp when the exchange rate was issued. */
    int64_t timestamp;

    friend bool operator==(const ExchangeRate& lhs, const ExchangeRate& rhs);
    friend bool operator!=(const ExchangeRate& lhs, const ExchangeRate& rhs);

    ExchangeRate(std::string id_,
                 std::string from_currency_,
                 std::string to_currency_,
                 ::zumo::Decimal value_,
                 int64_t valid_to_,
                 int64_t timestamp_)
    : id(std::move(id_))
    , from_currency(std::move(from_currency_))
    , to_currency(std::move(to_currency_))
    , value(std::move(value_))
    , valid_to(std::move(valid_to_))
    , timestamp(std::move(timestamp_))
    {}
};

}  // namespace zumo
