// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from state.djinni

#pragma once

#include "zumo/decimal.hpp"
#include <string>
#include <utility>

namespace zumo {

struct FeeRates final {
    ::zumo::Decimal slow;
    ::zumo::Decimal average;
    ::zumo::Decimal fast;
    float slow_time;
    float average_time;
    float fast_time;
    std::string source;

    friend bool operator==(const FeeRates& lhs, const FeeRates& rhs);
    friend bool operator!=(const FeeRates& lhs, const FeeRates& rhs);

    FeeRates(::zumo::Decimal slow_,
             ::zumo::Decimal average_,
             ::zumo::Decimal fast_,
             float slow_time_,
             float average_time_,
             float fast_time_,
             std::string source_)
    : slow(std::move(slow_))
    , average(std::move(average_))
    , fast(std::move(fast_))
    , slow_time(std::move(slow_time_))
    , average_time(std::move(average_time_))
    , fast_time(std::move(fast_time_))
    , source(std::move(source_))
    {}
};

}  // namespace zumo
