// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from networking.djinni

#pragma once

#include <memory>
#include <optional>
#include <string>
#include <unordered_map>

namespace zumo {

class HttpCallback;

class HttpProvider {
public:
    virtual ~HttpProvider() {}

    virtual void request(const std::string & url, const std::string & method, const std::unordered_map<std::string, std::string> & headers, const std::optional<std::string> & data, const std::shared_ptr<HttpCallback> & callback) = 0;
};

}  // namespace zumo
