// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from records.djinni

#pragma once

#include <string>
#include <utility>

namespace zumo {

/** Record containing Knowledge-Based Authentication (KBA) answer. */
struct KbaAnswer final {
    /** KBA question type, e.g. "FIRST_PET_NAME". */
    std::string type;
    /** KBA answer, e.g. "Shurik". */
    std::string answer;

    friend bool operator==(const KbaAnswer& lhs, const KbaAnswer& rhs);
    friend bool operator!=(const KbaAnswer& lhs, const KbaAnswer& rhs);

    KbaAnswer(std::string type_,
              std::string answer_)
    : type(std::move(type_))
    , answer(std::move(answer_))
    {}
};

}  // namespace zumo
