// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from records.djinni

#pragma once

#include <string>
#include <utility>

namespace zumo {

/** Record containing Knowledge-Based Authentication (KBA) question */
struct KbaQuestion final {
    /** KBA question type, e.g. "FIRST_PET_NAME" */
    std::string type;
    /** KBA question, e.g. "What was your first pet's name?" */
    std::string question;

    friend bool operator==(const KbaQuestion& lhs, const KbaQuestion& rhs);
    friend bool operator!=(const KbaQuestion& lhs, const KbaQuestion& rhs);

    KbaQuestion(std::string type_,
                std::string question_)
    : type(std::move(type_))
    , question(std::move(question_))
    {}
};

}  // namespace zumo
