// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from enums.djinni

#pragma once

#include <functional>

namespace zumo {

enum class LogLevel : int {
    TRACE,
    DEBUG,
    INFO,
    WARNING,
    ERROR,
    CRITICAL,
    OFF,
};

}  // namespace zumo

namespace std {

template <>
struct hash<::zumo::LogLevel> {
    size_t operator()(::zumo::LogLevel type) const {
        return std::hash<int>()(static_cast<int>(type));
    }
};

}  // namespace std
