// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from user.djinni

#pragma once

#include "zumo/exceptions.hpp"
#include <string>

namespace zumo {

/** Callback interface used by methods in @link User class. */
class MnemonicCallback {
public:
    virtual ~MnemonicCallback() {}

    virtual void on_error(const ::zumo::ZumoKitException & e) = 0;

    virtual void on_success(const std::string & mnemonic) = 0;
};

}  // namespace zumo
