// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from state.djinni

#pragma once

#include <string>
#include <utility>

namespace zumo {

struct NetworkType final {

    static std::string const MAINNET;

    static std::string const TESTNET;

    static std::string const ROPSTEN;

    static std::string const RINKEBY;

    static std::string const GOERLI;

    static std::string const KOVAN;
};

}  // namespace zumo
