// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from zumo_core.djinni

#pragma once

namespace zumo {

struct State;

class StateListener {
public:
    virtual ~StateListener() {}

    virtual void update(const State & state) = 0;
};

}  // namespace zumo
