// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from wallet.djinni

#pragma once

#include "zumo/exceptions.hpp"

namespace zumo {

struct Exchange;

/** Callback interface used by methods in Wallet class. */
class SubmitExchangeCallback {
public:
    virtual ~SubmitExchangeCallback() {}

    virtual void on_error(const ::zumo::ZumoKitException & e) = 0;

    virtual void on_success(const Exchange & exchage) = 0;
};

}  // namespace zumo
