// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from state.djinni

#pragma once

#include <string>
#include <utility>

namespace zumo {

struct TransactionDirection final {

    static std::string const INCOMING;

    static std::string const OUTGOING;
};

}  // namespace zumo
