// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from enums.djinni

#pragma once

#include <string>
#include <utility>

namespace zumo {

/** Transaction direction, 'SENT' or 'RECEIVED'. */
struct TransactionDirection final {

    static std::string const SENT;

    static std::string const RECEIVED;
};

}  // namespace zumo
