// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from enums.djinni

#pragma once

#include <string>
#include <utility>

namespace zumo {

/** Transaction direction, 'INCOMING' or 'OUTGOING'. */
struct TransactionDirection final {

    static std::string const INCOMING;

    static std::string const OUTGOING;
};

}  // namespace zumo
