// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from records.djinni

#pragma once

#include "zumo/decimal.hpp"
#include <string>
#include <utility>

namespace zumo {

/** Record containing crypto transaction fee rate */
struct TransactionFeeRate final {
    /** Fee rate resulting in slow confirmation time. */
    ::zumo::Decimal slow;
    /** Fee rate resulting in average confirmation time. */
    ::zumo::Decimal average;
    /** Fee rate resulting in fast confirmation time. */
    ::zumo::Decimal fast;
    /** Slow confirmation time in hours. */
    float slow_time;
    /** Average confirmation time in hours. */
    float average_time;
    /** Fast confirmation time in hours. */
    float fast_time;
    /** Fee rate information provider. */
    std::string source;

    friend bool operator==(const TransactionFeeRate& lhs, const TransactionFeeRate& rhs);
    friend bool operator!=(const TransactionFeeRate& lhs, const TransactionFeeRate& rhs);

    TransactionFeeRate(::zumo::Decimal slow_,
                       ::zumo::Decimal average_,
                       ::zumo::Decimal fast_,
                       float slow_time_,
                       float average_time_,
                       float fast_time_,
                       std::string source_)
    : slow(std::move(slow_))
    , average(std::move(average_))
    , fast(std::move(fast_))
    , slow_time(std::move(slow_time_))
    , average_time(std::move(average_time_))
    , fast_time(std::move(fast_time_))
    , source(std::move(source_))
    {}
};

}  // namespace zumo
