// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from enums.djinni

#pragma once

#include <string>
#include <utility>

namespace zumo {

/** Transaction type, 'CRYPTO', 'FIAT', 'NOMINATED' or 'CARD'. */
struct TransactionType final {

    static std::string const CRYPTO;

    static std::string const FIAT;

    static std::string const NOMINATED;

    static std::string const CARD;
};

}  // namespace zumo
