// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from state.djinni

#pragma once

#include <string>
#include <utility>

namespace zumo {

struct TransactionType final {

    static std::string const CRYPTO;

    static std::string const EXCHANGE;

    static std::string const FIAT;

    static std::string const NOMINATED;
};

}  // namespace zumo
