// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from user.djinni

#pragma once

#include <vector>

namespace zumo {

struct Account;
struct Transaction;

/** Callback interface used by methods in User class. */
class UserListener {
public:
    virtual ~UserListener() {}

    virtual void update(const std::vector<Account> & accounts, const std::vector<Transaction> & transactions) = 0;
};

}  // namespace zumo
