// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from zumo_core.djinni

#pragma once

#include "zumo/exceptions.hpp"
#include <memory>

namespace zumo {

class User;

/** Callback interface used by methods in ZumoKit class */
class UserCallback {
public:
    virtual ~UserCallback() {}

    virtual void on_error(const ::zumo::ZumoKitException & e) = 0;

    virtual void on_success(const std::shared_ptr<User> & user) = 0;
};

}  // namespace zumo
