// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from wallet.djinni

#pragma once

#include "decimal.hpp"
#include <cstdint>
#include <memory>
#include <optional>
#include <string>

namespace zumo {

class ComposeTransactionCallback;

/**
 * User wallet provides methods for transfer and exchange of fiat and cryptocurrency funds.
 * Sending a transaction or making an exchange is a two step process. First a transaction or
 * exchange has to be composed via one of the compose methods, then ComposedTransaction or
 * ComposedExchange can be submitted.
 * <p>
 * User wallet instance can be obtained by creating, unlocking or recovering user wallet via User instance.
 */
class Wallet {
public:
    virtual ~Wallet() {}

    /**
     * Compose BTC or BSV transaction. Refer to <a target="_top" href="https://developers.zumo.money/docs/guides/send-transactions#crypto">Send Transactions</a> guide for usage details.
     * <p>
     * On success ComposedTransaction  is returned via callback.
     *
     * @param from_account_id   Account identifier
     * @param change_account_id change Account identifier, which can be the same as from_account_id
     * @param destination       destination wallet address
     * @param amount            amount in BTC or BSV
     * @param fee_rate          fee rate in satoshis/byte
     * @param send_max          send maximum possible funds to destination
     * @param callback          an interface to receive the result or error
     */
    virtual void compose_transaction(const std::string & from_account_id, const std::string & change_account_id, const std::string & destination, const std::optional<::zumo::Decimal> & amount, const ::zumo::Decimal & fee_rate, bool send_max, const std::shared_ptr<ComposeTransactionCallback> & callback) = 0;

    /**
     * Compose Ethereum transaction. Refer to <a target="_top" href="https://developers.zumo.money/docs/guides/send-transactions#ethereum">Send Transactions</a> guide for usage details.
     * <p>
     * On success ComposedTransaction is returned via callback.
     *
     * @param from_account_id Account identifier
     * @param gas_price       gas price in gwei
     * @param gas_limit       gas limit
     * @param destination     destination wallet address
     * @param amount          amount in ETH
     * @param data            data in string format or null
     * @param nonce           next transaction nonce or null
     * @param send_max        send maximum possible funds to destination
     * @param callback        an interface to receive the result or error
     */
    virtual void compose_eth_transaction(const std::string & from_account_id, const ::zumo::Decimal & gas_price, int32_t gas_limit, const std::optional<std::string> & destination, const std::optional<::zumo::Decimal> & amount, const std::optional<std::string> & data, std::optional<int32_t> nonce, bool send_max, const std::shared_ptr<ComposeTransactionCallback> & callback) = 0;
};

}  // namespace zumo
