// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from user.djinni

#pragma once

#include <memory>
#include <string>

namespace zumo {

class Wallet;

class WalletCallback {
public:
    virtual ~WalletCallback() {}

    virtual void on_error(const std::string & error_name, const std::string & error_message) = 0;

    virtual void on_success(const std::shared_ptr<Wallet> & wallet) = 0;
};

}  // namespace zumo
