// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from user.djinni

#pragma once

#include "zumo/exceptions.hpp"
#include <memory>

namespace zumo {

class Wallet;

class WalletCallback {
public:
    virtual ~WalletCallback() {}

    virtual void on_error(const ::zumo::ZumoKitException & e) = 0;

    virtual void on_success(const std::shared_ptr<Wallet> & wallet) = 0;
};

}  // namespace zumo
