// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from networking.djinni

#pragma once

#include <string>

namespace zumo {

class WebSocketListener {
public:
    virtual ~WebSocketListener() {}

    virtual void on_open(const std::string & message) = 0;

    virtual void on_message(const std::string & message) = 0;

    virtual void on_close(const std::string & message) = 0;

    virtual void on_error(const std::string & message) = 0;
};

}  // namespace zumo
