// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from errors.djinni

#pragma once

#include <string>
#include <utility>

namespace zumo {

struct ZumoKitErrorType final {

    static std::string const API_CONNECTION_ERROR;

    static std::string const API_ERROR;

    static std::string const AUTHENTICATION_ERROR;

    static std::string const WALLET_ERROR;

    static std::string const INVALID_REQUEST_ERROR;

    static std::string const RATE_LIMIT_ERROR;

    static std::string const INVALID_ARGUMENT_ERROR;
};

}  // namespace zumo
