// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from user.djinni

#import "ZKAccount.h"
#import "ZKTransaction.h"
#import <Foundation/Foundation.h>


@protocol ZKAccountListener

- (void)update:(nullable ZKAccount *)account
  transactions:(nonnull NSArray<ZKTransaction *> *)transactions;

@end
