// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from records.djinni

#import <Foundation/Foundation.h>

/**
 * Record containing account's crypto related properties.
 * @see `ZKAccount`
 */
@interface ZKAccountCryptoProperties : NSObject
- (nonnull instancetype)initWithAddress:(nonnull NSString *)address
                                   path:(nonnull NSString *)path
                                  nonce:(nullable NSNumber *)nonce
                               utxoPool:(nullable NSString *)utxoPool
                                version:(int8_t)version;
+ (nonnull instancetype)accountCryptoPropertiesWithAddress:(nonnull NSString *)address
                                                      path:(nonnull NSString *)path
                                                     nonce:(nullable NSNumber *)nonce
                                                  utxoPool:(nullable NSString *)utxoPool
                                                   version:(int8_t)version;

/** Account crypto address. */
@property (nonatomic, readonly, nonnull) NSString * address;

/** Hierarchical Deterministic (HD) account derivation path. */
@property (nonatomic, readonly, nonnull) NSString * path;

/** Ethereum account nonce if greater than 0 or null otherwise. */
@property (nonatomic, readonly, nullable) NSNumber * nonce;

@property (nonatomic, readonly, nullable) NSString * utxoPool;

@property (nonatomic, readonly) int8_t version;

@end
