// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from user.djinni

#import "ZKAccount.h"
#import <Foundation/Foundation.h>


@protocol ZKAccountCallback

- (void)onError:(nonnull NSError *)e;

- (void)onSuccess:(nonnull ZKAccount *)account;

@end
