// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from user.djinni

#import "ZKAccountDataSnapshot.h"
#import <Foundation/Foundation.h>


/** Callback interface used by methods in `ZKUser` class. */
@protocol ZKAccountDataListener

- (void)onDataChange:(nonnull NSArray<ZKAccountDataSnapshot *> *)snapshots;

@end
