// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from state.djinni

#import "ZKAccountType.h"


NSString * __nonnull const ZKAccountTypeSTANDARD = @"STANDARD";

NSString * __nonnull const ZKAccountTypeCOMPATIBILITY = @"COMPATIBILITY";

NSString * __nonnull const ZKAccountTypeSEGWIT = @"SEGWIT";

@implementation ZKAccountType

- (nonnull instancetype)init
{
    if (self = [super init]) {
    }
    return self;
}

+ (nonnull instancetype)accountType
{
    return [(ZKAccountType*)[self alloc] init];
}

- (NSString *)description
{
    return [NSString stringWithFormat:@"<%@ %p>", self.class, (void *)self];
}

@end
