// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from records.djinni

#import <Foundation/Foundation.h>

/**
 * Record containing account's fiat related properties.
 * @see `ZKAccount`
 */
@interface ZKAccountFiatProperties : NSObject
- (nonnull instancetype)initWithProviderId:(nullable NSString *)providerId
                             accountNumber:(nullable NSString *)accountNumber
                                  sortCode:(nullable NSString *)sortCode
                                       bic:(nullable NSString *)bic
                                      iban:(nullable NSString *)iban
                              customerName:(nullable NSString *)customerName;
+ (nonnull instancetype)accountFiatPropertiesWithProviderId:(nullable NSString *)providerId
                                              accountNumber:(nullable NSString *)accountNumber
                                                   sortCode:(nullable NSString *)sortCode
                                                        bic:(nullable NSString *)bic
                                                       iban:(nullable NSString *)iban
                                               customerName:(nullable NSString *)customerName;

/** Fiat account provider id. */
@property (nonatomic, readonly, nullable) NSString * providerId;

/** Fiat account number or null. */
@property (nonatomic, readonly, nullable) NSString * accountNumber;

/** Fiat account sort code or null. */
@property (nonatomic, readonly, nullable) NSString * sortCode;

/** Fiat account BIC or null. */
@property (nonatomic, readonly, nullable) NSString * bic;

/** Fiat account IBAN or null. */
@property (nonatomic, readonly, nullable) NSString * iban;

/** Customer name or null. */
@property (nonatomic, readonly, nullable) NSString * customerName;

@end
