// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from records.djinni

#import "ZKAccountCryptoProperties.h"
#import "ZKAccountFiatProperties.h"
#import "ZKCard.h"
#import <Foundation/Foundation.h>

/** Record containing account details. */
@interface ZKAccount : NSObject
- (nonnull instancetype)initWithId:(nonnull NSString *)id
                      currencyType:(nonnull NSString *)currencyType
                      currencyCode:(nonnull NSString *)currencyCode
                           network:(nonnull NSString *)network
                              type:(nonnull NSString *)type
                       custodyType:(nonnull NSString *)custodyType
                           balance:(nonnull NSDecimalNumber *)balance
                     ledgerBalance:(nonnull NSDecimalNumber *)ledgerBalance
                  availableBalance:(nonnull NSDecimalNumber *)availableBalance
                    overdraftLimit:(nonnull NSDecimalNumber *)overdraftLimit
               hasNominatedAccount:(BOOL)hasNominatedAccount
                  cryptoProperties:(nullable ZKAccountCryptoProperties *)cryptoProperties
                    fiatProperties:(nullable ZKAccountFiatProperties *)fiatProperties
                             cards:(nonnull NSArray<ZKCard *> *)cards;
+ (nonnull instancetype)accountWithId:(nonnull NSString *)id
                         currencyType:(nonnull NSString *)currencyType
                         currencyCode:(nonnull NSString *)currencyCode
                              network:(nonnull NSString *)network
                                 type:(nonnull NSString *)type
                          custodyType:(nonnull NSString *)custodyType
                              balance:(nonnull NSDecimalNumber *)balance
                        ledgerBalance:(nonnull NSDecimalNumber *)ledgerBalance
                     availableBalance:(nonnull NSDecimalNumber *)availableBalance
                       overdraftLimit:(nonnull NSDecimalNumber *)overdraftLimit
                  hasNominatedAccount:(BOOL)hasNominatedAccount
                     cryptoProperties:(nullable ZKAccountCryptoProperties *)cryptoProperties
                       fiatProperties:(nullable ZKAccountFiatProperties *)fiatProperties
                                cards:(nonnull NSArray<ZKCard *> *)cards;

/** Unique account identifier. */
@property (nonatomic, readonly, nonnull) NSString * id;

/**
 * Account currency type.
 * @see `ZKCurrencyType`
 */
@property (nonatomic, readonly, nonnull) NSString * currencyType;

/**
 * Account currency code.
 * @see `ZKCurrencyCode`
 */
@property (nonatomic, readonly, nonnull) NSString * currencyCode;

/**
 * Account network type.
 * @see `ZKNetworkType`
 */
@property (nonatomic, readonly, nonnull) NSString * network;

/**
 * Account type.
 * @see `ZKAccountType`
 */
@property (nonatomic, readonly, nonnull) NSString * type;

/**
 * Custody type.
 * @see `ZKCustodyType`
 */
@property (nonatomic, readonly, nonnull) NSString * custodyType;

/** Account balance. */
@property (nonatomic, readonly, nonnull) NSDecimalNumber * balance;

/** Account ledger balance. */
@property (nonatomic, readonly, nonnull) NSDecimalNumber * ledgerBalance;

/** Account available balance, i.e. ledger balance minus pending transactions. */
@property (nonatomic, readonly, nonnull) NSDecimalNumber * availableBalance;

/** Overdraft limit. */
@property (nonatomic, readonly, nonnull) NSDecimalNumber * overdraftLimit;

/** Account has associated nominated account. */
@property (nonatomic, readonly) BOOL hasNominatedAccount;

/** Account crypto properties if account is a crypto account, otherwise null. */
@property (nonatomic, readonly, nullable) ZKAccountCryptoProperties * cryptoProperties;

/** Account fiat properties if account is a fiat account, otherwise null. */
@property (nonatomic, readonly, nullable) ZKAccountFiatProperties * fiatProperties;

/** Cards associated with this account. */
@property (nonatomic, readonly, nonnull) NSArray<ZKCard *> * cards;

@end
