// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from records.djinni

#import "ZKAccountCryptoProperties.h"


@implementation ZKAccountCryptoProperties

- (nonnull instancetype)initWithAddress:(nonnull NSString *)address
                                   path:(nonnull NSString *)path
                                  nonce:(nullable NSNumber *)nonce
{
    if (self = [super init]) {
        _address = [address copy];
        _path = [path copy];
        _nonce = nonce;
    }
    return self;
}

+ (nonnull instancetype)accountCryptoPropertiesWithAddress:(nonnull NSString *)address
                                                      path:(nonnull NSString *)path
                                                     nonce:(nullable NSNumber *)nonce
{
    return [(ZKAccountCryptoProperties*)[self alloc] initWithAddress:address
                                                                path:path
                                                               nonce:nonce];
}

- (BOOL)isEqual:(id)other
{
    if (![other isKindOfClass:[ZKAccountCryptoProperties class]]) {
        return NO;
    }
    ZKAccountCryptoProperties *typedOther = (ZKAccountCryptoProperties *)other;
    return [self.address isEqualToString:typedOther.address] &&
            [self.path isEqualToString:typedOther.path] &&
            ((self.nonce == nil && typedOther.nonce == nil) || (self.nonce != nil && [self.nonce isEqual:typedOther.nonce]));
}

- (NSUInteger)hash
{
    return NSStringFromClass([self class]).hash ^
            self.address.hash ^
            self.path.hash ^
            self.nonce.hash;
}

- (NSString *)description
{
    return [NSString stringWithFormat:@"<%@ %p address:%@ path:%@ nonce:%@>", self.class, (void *)self, self.address, self.path, self.nonce];
}

@end
