// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from records.djinni

#import <Foundation/Foundation.h>

/** Record describing user address details */
@interface ZKAddress : NSObject
- (nonnull instancetype)initWithHouseNumber:(nonnull NSString *)houseNumber
                               addressLine1:(nonnull NSString *)addressLine1
                               addressLine2:(nullable NSString *)addressLine2
                                    country:(nonnull NSString *)country
                                   postCode:(nonnull NSString *)postCode
                                   postTown:(nonnull NSString *)postTown;
+ (nonnull instancetype)addressWithHouseNumber:(nonnull NSString *)houseNumber
                                  addressLine1:(nonnull NSString *)addressLine1
                                  addressLine2:(nullable NSString *)addressLine2
                                       country:(nonnull NSString *)country
                                      postCode:(nonnull NSString *)postCode
                                      postTown:(nonnull NSString *)postTown;

/** House number. */
@property (nonatomic, readonly, nonnull) NSString * houseNumber;

/** First line of address. */
@property (nonatomic, readonly, nonnull) NSString * addressLine1;

/** Second line of address or null. */
@property (nonatomic, readonly, nullable) NSString * addressLine2;

/** Country code in ISO 3166-1 Alpha-2 format, e.g. 'GB'. */
@property (nonatomic, readonly, nonnull) NSString * country;

/** Post code. */
@property (nonatomic, readonly, nonnull) NSString * postCode;

/** Post town */
@property (nonatomic, readonly, nonnull) NSString * postTown;

@end
