// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from enums.djinni

#import "ZKCardType.h"


NSString * __nonnull const ZKCardTypeVIRTUAL = @"VIRTUAL";

NSString * __nonnull const ZKCardTypePHYSICAL = @"PHYSICAL";

@implementation ZKCardType

- (nonnull instancetype)init
{
    if (self = [super init]) {
    }
    return self;
}

+ (nonnull instancetype)cardType
{
    return [(ZKCardType*)[self alloc] init];
}

- (NSString *)description
{
    return [NSString stringWithFormat:@"<%@ %p>", self.class, (void *)self];
}

@end
