// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from records.djinni

#import "ZKCardDetails.h"


@implementation ZKCardDetails

- (nonnull instancetype)initWithPan:(nonnull NSString *)pan
                               cvv2:(nonnull NSString *)cvv2
                             expiry:(nonnull NSString *)expiry
{
    if (self = [super init]) {
        _pan = [pan copy];
        _cvv2 = [cvv2 copy];
        _expiry = [expiry copy];
    }
    return self;
}

+ (nonnull instancetype)cardDetailsWithPan:(nonnull NSString *)pan
                                      cvv2:(nonnull NSString *)cvv2
                                    expiry:(nonnull NSString *)expiry
{
    return [(ZKCardDetails*)[self alloc] initWithPan:pan
                                                cvv2:cvv2
                                              expiry:expiry];
}

- (BOOL)isEqual:(id)other
{
    if (![other isKindOfClass:[ZKCardDetails class]]) {
        return NO;
    }
    ZKCardDetails *typedOther = (ZKCardDetails *)other;
    return [self.pan isEqualToString:typedOther.pan] &&
            [self.cvv2 isEqualToString:typedOther.cvv2] &&
            [self.expiry isEqualToString:typedOther.expiry];
}

- (NSUInteger)hash
{
    return NSStringFromClass([self class]).hash ^
            self.pan.hash ^
            self.cvv2.hash ^
            self.expiry.hash;
}

- (NSString *)description
{
    return [NSString stringWithFormat:@"<%@ %p pan:%@ cvv2:%@ expiry:%@>", self.class, (void *)self, self.pan, self.cvv2, self.expiry];
}

@end
