// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from enums.djinni

#import <Foundation/Foundation.h>

/** Card type, 'VIRTUAL' or 'PHYSICAL'. */
@interface ZKCardType : NSObject
- (nonnull instancetype)init;
+ (nonnull instancetype)cardType;

@end

extern NSString * __nonnull const ZKCardTypeVIRTUAL;
extern NSString * __nonnull const ZKCardTypePHYSICAL;
