// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from user.djinni

#import "ZKCardDetails.h"
#import <Foundation/Foundation.h>


/** Callback interface used by methods in `ZKUser` class. */
@protocol ZKCardDetailsCallback

- (void)onError:(nonnull NSError *)e;

- (void)onSuccess:(nonnull ZKCardDetails *)cardDetails;

@end
