// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from records.djinni

#import <Foundation/Foundation.h>

/** Record containing basic card details. */
@interface ZKCard : NSObject
- (nonnull instancetype)initWithId:(nonnull NSString *)id
                         accountId:(nonnull NSString *)accountId
                          cardType:(nonnull NSString *)cardType
                        cardStatus:(nonnull NSString *)cardStatus
                             limit:(int32_t)limit
                         maskedPan:(nonnull NSString *)maskedPan
                            expiry:(nonnull NSString *)expiry;
+ (nonnull instancetype)cardWithId:(nonnull NSString *)id
                         accountId:(nonnull NSString *)accountId
                          cardType:(nonnull NSString *)cardType
                        cardStatus:(nonnull NSString *)cardStatus
                             limit:(int32_t)limit
                         maskedPan:(nonnull NSString *)maskedPan
                            expiry:(nonnull NSString *)expiry;

/** Unique card identifier. */
@property (nonatomic, readonly, nonnull) NSString * id;

/** Associated account's identifier. */
@property (nonatomic, readonly, nonnull) NSString * accountId;

/**
 * Card type.
 * @see `ZKCardType.`
 */
@property (nonatomic, readonly, nonnull) NSString * cardType;

/**
 * Current card status.
 * @see `ZKCardStatus`
 */
@property (nonatomic, readonly, nonnull) NSString * cardStatus;

/** Current card limit. */
@property (nonatomic, readonly) int32_t limit;

/** Card masked pan, e.g **** **** **** 5454. */
@property (nonatomic, readonly, nonnull) NSString * maskedPan;

/** Card year and month of expiry, e.g. 2024-08. */
@property (nonatomic, readonly, nonnull) NSString * expiry;

@end
