// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from enums.djinni

#import <Foundation/Foundation.h>

/** Card status, for example 'ACTIVE'. */
@interface ZKCardStatus : NSObject
- (nonnull instancetype)init;
+ (nonnull instancetype)cardStatus;

@end

extern NSString * __nonnull const ZKCardStatusCREATED;
extern NSString * __nonnull const ZKCardStatusACTIVE;
extern NSString * __nonnull const ZKCardStatusBLOCKED;
extern NSString * __nonnull const ZKCardStatusSUSPENDED;
extern NSString * __nonnull const ZKCardStatusEXPIRED;
extern NSString * __nonnull const ZKCardStatusCANCELLED;
