// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from zumo_core.djinni

#import <Foundation/Foundation.h>


/** Callback interface used to listen for changes in `ZKZumoKit` class. */
@protocol ZKChangeListener

- (void)onChange;

@end
