// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from state.djinni

#import "ZKAccount.h"
#import <Foundation/Foundation.h>

@interface ZKComposedTransaction : NSObject
- (nonnull instancetype)initWithSignedTransaction:(nonnull NSString *)signedTransaction
                                          account:(nonnull ZKAccount *)account
                                      destination:(nullable NSString *)destination
                                           amount:(nullable NSString *)amount
                                             data:(nullable NSString *)data
                                              fee:(nonnull NSString *)fee;
+ (nonnull instancetype)composedTransactionWithSignedTransaction:(nonnull NSString *)signedTransaction
                                                         account:(nonnull ZKAccount *)account
                                                     destination:(nullable NSString *)destination
                                                          amount:(nullable NSString *)amount
                                                            data:(nullable NSString *)data
                                                             fee:(nonnull NSString *)fee;

@property (nonatomic, readonly, nonnull) NSString * signedTransaction;

@property (nonatomic, readonly, nonnull) ZKAccount * account;

@property (nonatomic, readonly, nullable) NSString * destination;

@property (nonatomic, readonly, nullable) NSString * amount;

@property (nonatomic, readonly, nullable) NSString * data;

@property (nonatomic, readonly, nonnull) NSString * fee;

@end
