// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from wallet.djinni

#import "ZKComposedTransaction.h"
#import <Foundation/Foundation.h>


@protocol ZKComposeTransactionCallback

- (void)onError:(nonnull NSError *)e;

- (void)onSuccess:(nonnull ZKComposedTransaction *)composedTransaction;

@end
