// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from state.djinni

#import "ZKAccount.h"
#import "ZKExchangeRate.h"
#import "ZKExchangeSettings.h"
#import <Foundation/Foundation.h>

@interface ZKComposedExchange : NSObject
- (nonnull instancetype)initWithSignedTransaction:(nullable NSString *)signedTransaction
                                   depositAccount:(nonnull ZKAccount *)depositAccount
                                  withdrawAccount:(nonnull ZKAccount *)withdrawAccount
                                     exchangeRate:(nonnull ZKExchangeRate *)exchangeRate
                                 exchangeSettings:(nonnull ZKExchangeSettings *)exchangeSettings
                                  exchangeAddress:(nullable NSString *)exchangeAddress
                                            value:(nonnull NSString *)value
                                      returnValue:(nonnull NSString *)returnValue
                                       depositFee:(nonnull NSString *)depositFee
                                      exchangeFee:(nonnull NSString *)exchangeFee
                                      withdrawFee:(nonnull NSString *)withdrawFee
                                            nonce:(nullable NSString *)nonce;
+ (nonnull instancetype)composedExchangeWithSignedTransaction:(nullable NSString *)signedTransaction
                                               depositAccount:(nonnull ZKAccount *)depositAccount
                                              withdrawAccount:(nonnull ZKAccount *)withdrawAccount
                                                 exchangeRate:(nonnull ZKExchangeRate *)exchangeRate
                                             exchangeSettings:(nonnull ZKExchangeSettings *)exchangeSettings
                                              exchangeAddress:(nullable NSString *)exchangeAddress
                                                        value:(nonnull NSString *)value
                                                  returnValue:(nonnull NSString *)returnValue
                                                   depositFee:(nonnull NSString *)depositFee
                                                  exchangeFee:(nonnull NSString *)exchangeFee
                                                  withdrawFee:(nonnull NSString *)withdrawFee
                                                        nonce:(nullable NSString *)nonce;

@property (nonatomic, readonly, nullable) NSString * signedTransaction;

@property (nonatomic, readonly, nonnull) ZKAccount * depositAccount;

@property (nonatomic, readonly, nonnull) ZKAccount * withdrawAccount;

@property (nonatomic, readonly, nonnull) ZKExchangeRate * exchangeRate;

@property (nonatomic, readonly, nonnull) ZKExchangeSettings * exchangeSettings;

@property (nonatomic, readonly, nullable) NSString * exchangeAddress;

@property (nonatomic, readonly, nonnull) NSString * value;

@property (nonatomic, readonly, nonnull) NSString * returnValue;

@property (nonatomic, readonly, nonnull) NSString * depositFee;

@property (nonatomic, readonly, nonnull) NSString * exchangeFee;

@property (nonatomic, readonly, nonnull) NSString * withdrawFee;

@property (nonatomic, readonly, nullable) NSString * nonce;

@end
