// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from records.djinni

#import "ZKComposedExchange.h"


@implementation ZKComposedExchange

- (nonnull instancetype)initWithDebitAccount:(nonnull ZKAccount *)debitAccount
                               creditAccount:(nonnull ZKAccount *)creditAccount
                                       quote:(nonnull ZKQuote *)quote
{
    if (self = [super init]) {
        _debitAccount = debitAccount;
        _creditAccount = creditAccount;
        _quote = quote;
    }
    return self;
}

+ (nonnull instancetype)composedExchangeWithDebitAccount:(nonnull ZKAccount *)debitAccount
                                           creditAccount:(nonnull ZKAccount *)creditAccount
                                                   quote:(nonnull ZKQuote *)quote
{
    return [(ZKComposedExchange*)[self alloc] initWithDebitAccount:debitAccount
                                                     creditAccount:creditAccount
                                                             quote:quote];
}

- (BOOL)isEqual:(id)other
{
    if (![other isKindOfClass:[ZKComposedExchange class]]) {
        return NO;
    }
    ZKComposedExchange *typedOther = (ZKComposedExchange *)other;
    return [self.debitAccount isEqual:typedOther.debitAccount] &&
            [self.creditAccount isEqual:typedOther.creditAccount] &&
            [self.quote isEqual:typedOther.quote];
}

- (NSUInteger)hash
{
    return NSStringFromClass([self class]).hash ^
            self.debitAccount.hash ^
            self.creditAccount.hash ^
            self.quote.hash;
}

- (NSString *)description
{
    return [NSString stringWithFormat:@"<%@ %p debitAccount:%@ creditAccount:%@ quote:%@>", self.class, (void *)self, self.debitAccount, self.creditAccount, self.quote];
}

@end
