// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from records.djinni

#import "ZKAccount.h"
#import "ZKExchangeSetting.h"
#import "ZKQuote.h"
#import <Foundation/Foundation.h>

/** Record containing result of the compose exchange method on `ZKWallet` object. */
@interface ZKComposedExchange : NSObject
- (nonnull instancetype)initWithSignedTransaction:(nullable NSString *)signedTransaction
                                      fromAccount:(nonnull ZKAccount *)fromAccount
                                        toAccount:(nonnull ZKAccount *)toAccount
                                            quote:(nonnull ZKQuote *)quote
                                  exchangeSetting:(nonnull ZKExchangeSetting *)exchangeSetting
                                  exchangeAddress:(nullable NSString *)exchangeAddress
                                           amount:(nonnull NSDecimalNumber *)amount
                                     returnAmount:(nonnull NSDecimalNumber *)returnAmount
                           outgoingTransactionFee:(nonnull NSDecimalNumber *)outgoingTransactionFee
                                      exchangeFee:(nonnull NSDecimalNumber *)exchangeFee
                             returnTransactionFee:(nonnull NSDecimalNumber *)returnTransactionFee
                                            nonce:(nonnull NSString *)nonce;
+ (nonnull instancetype)composedExchangeWithSignedTransaction:(nullable NSString *)signedTransaction
                                                  fromAccount:(nonnull ZKAccount *)fromAccount
                                                    toAccount:(nonnull ZKAccount *)toAccount
                                                        quote:(nonnull ZKQuote *)quote
                                              exchangeSetting:(nonnull ZKExchangeSetting *)exchangeSetting
                                              exchangeAddress:(nullable NSString *)exchangeAddress
                                                       amount:(nonnull NSDecimalNumber *)amount
                                                 returnAmount:(nonnull NSDecimalNumber *)returnAmount
                                       outgoingTransactionFee:(nonnull NSDecimalNumber *)outgoingTransactionFee
                                                  exchangeFee:(nonnull NSDecimalNumber *)exchangeFee
                                         returnTransactionFee:(nonnull NSDecimalNumber *)returnTransactionFee
                                                        nonce:(nonnull NSString *)nonce;

/** Signed transaction for a crypto transaction, null otherwise. */
@property (nonatomic, readonly, nullable) NSString * signedTransaction;

/** Source account. */
@property (nonatomic, readonly, nonnull) ZKAccount * fromAccount;

/** Target account. */
@property (nonatomic, readonly, nonnull) ZKAccount * toAccount;

/** Exchange rate quote used when composing exchange. */
@property (nonatomic, readonly, nonnull) ZKQuote * quote;

/** Exchange setting used when composing exchange. */
@property (nonatomic, readonly, nonnull) ZKExchangeSetting * exchangeSetting;

/**
 * Zumo Exchange Service wallet address where outgoing crypto funds were deposited,
 * null for exchanges from fiat currencies.
 */
@property (nonatomic, readonly, nullable) NSString * exchangeAddress;

/** Exchange amount in source account currency. */
@property (nonatomic, readonly, nonnull) NSDecimalNumber * amount;

/**
 * Amount that user receives, calculated as <code>value X quote.value X (1 - feeRate) - returnTransactionFee</code>.
 * @see `ZKExchangeSetting`
 */
@property (nonatomic, readonly, nonnull) NSDecimalNumber * returnAmount;

/** Outgoing transaction fee. */
@property (nonatomic, readonly, nonnull) NSDecimalNumber * outgoingTransactionFee;

/**
 * Exchange fee, calculated as <code>value X quote.value X exchangeFeeRate</code>.
 * @see `ZKExchangeSetting`
 */
@property (nonatomic, readonly, nonnull) NSDecimalNumber * exchangeFee;

/**
 * Return transaction fee.
 * @see `ZKExchangeSetting`
 */
@property (nonatomic, readonly, nonnull) NSDecimalNumber * returnTransactionFee;

/** Unique nonce used to prevent double spend. */
@property (nonatomic, readonly, nonnull) NSString * nonce;

@end
