// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from state.djinni

#import <Foundation/Foundation.h>

@interface ZKCryptoDetails : NSObject
- (nonnull instancetype)initWithTxHash:(nullable NSString *)txHash
                                 nonce:(nullable NSNumber *)nonce
                           fromAddress:(nonnull NSString *)fromAddress
                             toAddress:(nullable NSString *)toAddress
                                  data:(nullable NSString *)data
                              gasPrice:(nullable NSString *)gasPrice
                              gasLimit:(nullable NSString *)gasLimit
                            fiatAmount:(nonnull NSDictionary<NSString *, NSString *> *)fiatAmount
                               fiatFee:(nonnull NSDictionary<NSString *, NSString *> *)fiatFee;
+ (nonnull instancetype)cryptoDetailsWithTxHash:(nullable NSString *)txHash
                                          nonce:(nullable NSNumber *)nonce
                                    fromAddress:(nonnull NSString *)fromAddress
                                      toAddress:(nullable NSString *)toAddress
                                           data:(nullable NSString *)data
                                       gasPrice:(nullable NSString *)gasPrice
                                       gasLimit:(nullable NSString *)gasLimit
                                     fiatAmount:(nonnull NSDictionary<NSString *, NSString *> *)fiatAmount
                                        fiatFee:(nonnull NSDictionary<NSString *, NSString *> *)fiatFee;

@property (nonatomic, readonly, nullable) NSString * txHash;

@property (nonatomic, readonly, nullable) NSNumber * nonce;

@property (nonatomic, readonly, nonnull) NSString * fromAddress;

@property (nonatomic, readonly, nullable) NSString * toAddress;

@property (nonatomic, readonly, nullable) NSString * data;

@property (nonatomic, readonly, nullable) NSString * gasPrice;

@property (nonatomic, readonly, nullable) NSString * gasLimit;

@property (nonatomic, readonly, nonnull) NSDictionary<NSString *, NSString *> * fiatAmount;

@property (nonatomic, readonly, nonnull) NSDictionary<NSString *, NSString *> * fiatFee;

@end
