// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from enums.djinni

#import "ZKCurrencyCode.h"


NSString * __nonnull const ZKCurrencyCodeGBP = @"GBP";

NSString * __nonnull const ZKCurrencyCodeETH = @"ETH";

NSString * __nonnull const ZKCurrencyCodeBTC = @"BTC";

NSString * __nonnull const ZKCurrencyCodeBSV = @"BSV";

@implementation ZKCurrencyCode

- (nonnull instancetype)init
{
    if (self = [super init]) {
    }
    return self;
}

+ (nonnull instancetype)currencyCode
{
    return [(ZKCurrencyCode*)[self alloc] init];
}

- (NSString *)description
{
    return [NSString stringWithFormat:@"<%@ %p>", self.class, (void *)self];
}

@end
