// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from state.djinni

#import <Foundation/Foundation.h>

@interface ZKCurrencyType : NSObject
- (nonnull instancetype)init;
+ (nonnull instancetype)currencyType;

@end

extern NSString * __nonnull const ZKCurrencyTypeFIAT;
extern NSString * __nonnull const ZKCurrencyTypeCRYPTO;
