// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from state.djinni

#import <Foundation/Foundation.h>

@interface ZKCurrencyCode : NSObject
- (nonnull instancetype)init;
+ (nonnull instancetype)currencyCode;

@end

extern NSString * __nonnull const ZKCurrencyCodeGBP;
extern NSString * __nonnull const ZKCurrencyCodeUSD;
extern NSString * __nonnull const ZKCurrencyCodeETH;
extern NSString * __nonnull const ZKCurrencyCodeBTC;
