// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from enums.djinni

#import <Foundation/Foundation.h>

/** Curency type, 'FIAT' or 'CRYPTO'. */
@interface ZKCurrencyType : NSObject
- (nonnull instancetype)init;
+ (nonnull instancetype)currencyType;

@end

extern NSString * __nonnull const ZKCurrencyTypeFIAT;
extern NSString * __nonnull const ZKCurrencyTypeCRYPTO;
