// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from state.djinni

#import "ZKExchangeStatus.h"
#import <Foundation/Foundation.h>

@interface ZKExchange : NSObject
- (nonnull instancetype)initWithId:(nonnull NSString *)id
                            status:(ZKExchangeStatus)status
                   depositCurrency:(nonnull NSString *)depositCurrency
                  depositAccountId:(nonnull NSString *)depositAccountId
              depositTransactionId:(nonnull NSString *)depositTransactionId
                  withdrawCurrency:(nonnull NSString *)withdrawCurrency
                 withdrawAccountId:(nonnull NSString *)withdrawAccountId
             withdrawTransactionId:(nullable NSString *)withdrawTransactionId
                            amount:(nonnull NSString *)amount
                      returnAmount:(nonnull NSString *)returnAmount
                       submittedAt:(nullable NSNumber *)submittedAt
                       confirmedAt:(nullable NSNumber *)confirmedAt;
+ (nonnull instancetype)exchangeWithId:(nonnull NSString *)id
                                status:(ZKExchangeStatus)status
                       depositCurrency:(nonnull NSString *)depositCurrency
                      depositAccountId:(nonnull NSString *)depositAccountId
                  depositTransactionId:(nonnull NSString *)depositTransactionId
                      withdrawCurrency:(nonnull NSString *)withdrawCurrency
                     withdrawAccountId:(nonnull NSString *)withdrawAccountId
                 withdrawTransactionId:(nullable NSString *)withdrawTransactionId
                                amount:(nonnull NSString *)amount
                          returnAmount:(nonnull NSString *)returnAmount
                           submittedAt:(nullable NSNumber *)submittedAt
                           confirmedAt:(nullable NSNumber *)confirmedAt;

@property (nonatomic, readonly, nonnull) NSString * id;

@property (nonatomic, readonly) ZKExchangeStatus status;

@property (nonatomic, readonly, nonnull) NSString * depositCurrency;

@property (nonatomic, readonly, nonnull) NSString * depositAccountId;

@property (nonatomic, readonly, nonnull) NSString * depositTransactionId;

@property (nonatomic, readonly, nonnull) NSString * withdrawCurrency;

@property (nonatomic, readonly, nonnull) NSString * withdrawAccountId;

@property (nonatomic, readonly, nullable) NSString * withdrawTransactionId;

@property (nonatomic, readonly, nonnull) NSString * amount;

@property (nonatomic, readonly, nonnull) NSString * returnAmount;

@property (nonatomic, readonly, nullable) NSNumber * submittedAt;

@property (nonatomic, readonly, nullable) NSNumber * confirmedAt;

@end
