// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from state.djinni

#import <Foundation/Foundation.h>

@interface ZKExchangeFees : NSObject
- (nonnull instancetype)initWithId:(nonnull NSString *)id
                   depositCurrency:(nonnull NSString *)depositCurrency
                  withdrawCurrency:(nonnull NSString *)withdrawCurrency
                           feeRate:(nonnull NSString *)feeRate
                    depositFeeRate:(nonnull NSString *)depositFeeRate
                       withdrawFee:(nonnull NSString *)withdrawFee
                         timestamp:(int64_t)timestamp;
+ (nonnull instancetype)exchangeFeesWithId:(nonnull NSString *)id
                           depositCurrency:(nonnull NSString *)depositCurrency
                          withdrawCurrency:(nonnull NSString *)withdrawCurrency
                                   feeRate:(nonnull NSString *)feeRate
                            depositFeeRate:(nonnull NSString *)depositFeeRate
                               withdrawFee:(nonnull NSString *)withdrawFee
                                 timestamp:(int64_t)timestamp;

@property (nonatomic, readonly, nonnull) NSString * id;

@property (nonatomic, readonly, nonnull) NSString * depositCurrency;

@property (nonatomic, readonly, nonnull) NSString * withdrawCurrency;

@property (nonatomic, readonly, nonnull) NSString * feeRate;

@property (nonatomic, readonly, nonnull) NSString * depositFeeRate;

@property (nonatomic, readonly, nonnull) NSString * withdrawFee;

@property (nonatomic, readonly) int64_t timestamp;

@end
