// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from state.djinni

#import <Foundation/Foundation.h>

@interface ZKExchangeStatus : NSObject
- (nonnull instancetype)init;
+ (nonnull instancetype)exchangeStatus;

@end

extern NSString * __nonnull const ZKExchangeStatusPENDING;
extern NSString * __nonnull const ZKExchangeStatusDEPOSITED;
extern NSString * __nonnull const ZKExchangeStatusCONFIRMED;
extern NSString * __nonnull const ZKExchangeStatusFAILED;
extern NSString * __nonnull const ZKExchangeStatusRESUBMITTED;
extern NSString * __nonnull const ZKExchangeStatusCANCELLED;
extern NSString * __nonnull const ZKExchangeStatusPAUSED;
