// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from records.djinni

#import "ZKExchangeRate.h"
#import "ZKExchangeSettings.h"
#import <Foundation/Foundation.h>

/** Record containing exchange details. */
@interface ZKExchange : NSObject
- (nonnull instancetype)initWithId:(nonnull NSString *)id
                            status:(nonnull NSString *)status
                      fromCurrency:(nonnull NSString *)fromCurrency
                     fromAccountId:(nonnull NSString *)fromAccountId
             outgoingTransactionId:(nullable NSString *)outgoingTransactionId
                        toCurrency:(nonnull NSString *)toCurrency
                       toAccountId:(nonnull NSString *)toAccountId
               returnTransactionId:(nullable NSString *)returnTransactionId
                            amount:(nonnull NSDecimalNumber *)amount
            outgoingTransactionFee:(nullable NSDecimalNumber *)outgoingTransactionFee
                      returnAmount:(nonnull NSDecimalNumber *)returnAmount
                       exchangeFee:(nonnull NSDecimalNumber *)exchangeFee
              returnTransactionFee:(nonnull NSDecimalNumber *)returnTransactionFee
                      exchangeRate:(nonnull ZKExchangeRate *)exchangeRate
                  exchangeSettings:(nonnull ZKExchangeSettings *)exchangeSettings
                     exchangeRates:(nonnull NSDictionary<NSString *, NSDictionary<NSString *, ZKExchangeRate *> *> *)exchangeRates
                             nonce:(nullable NSString *)nonce
                       submittedAt:(nullable NSNumber *)submittedAt
                       confirmedAt:(nullable NSNumber *)confirmedAt;
+ (nonnull instancetype)exchangeWithId:(nonnull NSString *)id
                                status:(nonnull NSString *)status
                          fromCurrency:(nonnull NSString *)fromCurrency
                         fromAccountId:(nonnull NSString *)fromAccountId
                 outgoingTransactionId:(nullable NSString *)outgoingTransactionId
                            toCurrency:(nonnull NSString *)toCurrency
                           toAccountId:(nonnull NSString *)toAccountId
                   returnTransactionId:(nullable NSString *)returnTransactionId
                                amount:(nonnull NSDecimalNumber *)amount
                outgoingTransactionFee:(nullable NSDecimalNumber *)outgoingTransactionFee
                          returnAmount:(nonnull NSDecimalNumber *)returnAmount
                           exchangeFee:(nonnull NSDecimalNumber *)exchangeFee
                  returnTransactionFee:(nonnull NSDecimalNumber *)returnTransactionFee
                          exchangeRate:(nonnull ZKExchangeRate *)exchangeRate
                      exchangeSettings:(nonnull ZKExchangeSettings *)exchangeSettings
                         exchangeRates:(nonnull NSDictionary<NSString *, NSDictionary<NSString *, ZKExchangeRate *> *> *)exchangeRates
                                 nonce:(nullable NSString *)nonce
                           submittedAt:(nullable NSNumber *)submittedAt
                           confirmedAt:(nullable NSNumber *)confirmedAt;

/** Identifier */
@property (nonatomic, readonly, nonnull) NSString * id;

/**
 * Exchange status.
 * @see `ZKExchangeStatus`
 */
@property (nonatomic, readonly, nonnull) NSString * status;

/**
 * Currency from which exchange was made.
 * @see `ZKCurrencyCode`
 */
@property (nonatomic, readonly, nonnull) NSString * fromCurrency;

/** Source `ZKAccount` identifier. */
@property (nonatomic, readonly, nonnull) NSString * fromAccountId;

/** Outgoing `ZKTransaction` identifier. */
@property (nonatomic, readonly, nullable) NSString * outgoingTransactionId;

/**
 * Currency to which exchange was made.
 * @see `ZKCurrencyCode`
 */
@property (nonatomic, readonly, nonnull) NSString * toCurrency;

/** Target `ZKAccount` identifier. */
@property (nonatomic, readonly, nonnull) NSString * toAccountId;

/** Return `ZKTransaction` identifier. */
@property (nonatomic, readonly, nullable) NSString * returnTransactionId;

/** Amount in deposit currency. */
@property (nonatomic, readonly, nonnull) NSDecimalNumber * amount;

/** Outgoing transaction fee. */
@property (nonatomic, readonly, nullable) NSDecimalNumber * outgoingTransactionFee;

/**
 * Amount that user receives, calculated as <code>amount X exchangeRate X (1 - feeRate) - returnTransactionFee</code>.
 * @see `ZKExchangeSettings`
 */
@property (nonatomic, readonly, nonnull) NSDecimalNumber * returnAmount;

/**
 * Exchange fee, calculated as <code>amount X exchangeRate X exchangeFeeRate</code>.
 * @see `ZKExchangeSettings`
 */
@property (nonatomic, readonly, nonnull) NSDecimalNumber * exchangeFee;

/**
 * Return transaction fee.
 * @see `ZKExchangeSettings`
 */
@property (nonatomic, readonly, nonnull) NSDecimalNumber * returnTransactionFee;

/** Exchange rate used. */
@property (nonatomic, readonly, nonnull) ZKExchangeRate * exchangeRate;

/** Exchange settings used. */
@property (nonatomic, readonly, nonnull) ZKExchangeSettings * exchangeSettings;

/**
 * Exchange rates at the time exchange was made.
 * This can be used to display amounts in local currency to the user.
 */
@property (nonatomic, readonly, nonnull) NSDictionary<NSString *, NSDictionary<NSString *, ZKExchangeRate *> *> * exchangeRates;

/** Exchange nonce or null. Used to prevent double spend. */
@property (nonatomic, readonly, nullable) NSString * nonce;

/** Epoch timestamp when transaction was submitted. */
@property (nonatomic, readonly, nullable) NSNumber * submittedAt;

/** Epoch timestamp when transaction was confirmed or null if not yet confirmed. */
@property (nonatomic, readonly, nullable) NSNumber * confirmedAt;

@end
