// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from enums.djinni

#import "ZKExchangeStatus.h"


NSString * __nonnull const ZKExchangeStatusPENDING = @"PENDING";

NSString * __nonnull const ZKExchangeStatusWITHDRAWING = @"WITHDRAWING";

NSString * __nonnull const ZKExchangeStatusCONFIRMED = @"CONFIRMED";

NSString * __nonnull const ZKExchangeStatusFAILED = @"FAILED";

@implementation ZKExchangeStatus

- (nonnull instancetype)init
{
    if (self = [super init]) {
    }
    return self;
}

+ (nonnull instancetype)exchangeStatus
{
    return [(ZKExchangeStatus*)[self alloc] init];
}

- (NSString *)description
{
    return [NSString stringWithFormat:@"<%@ %p>", self.class, (void *)self];
}

@end
