// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from state.djinni

#import <Foundation/Foundation.h>

@interface ZKFeeRates : NSObject
- (nonnull instancetype)initWithSlow:(nonnull NSDecimalNumber *)slow
                             average:(nonnull NSDecimalNumber *)average
                                fast:(nonnull NSDecimalNumber *)fast
                            slowTime:(float)slowTime
                         averageTime:(float)averageTime
                            fastTime:(float)fastTime
                              source:(nonnull NSString *)source;
+ (nonnull instancetype)feeRatesWithSlow:(nonnull NSDecimalNumber *)slow
                                 average:(nonnull NSDecimalNumber *)average
                                    fast:(nonnull NSDecimalNumber *)fast
                                slowTime:(float)slowTime
                             averageTime:(float)averageTime
                                fastTime:(float)fastTime
                                  source:(nonnull NSString *)source;

@property (nonatomic, readonly, nonnull) NSDecimalNumber * slow;

@property (nonatomic, readonly, nonnull) NSDecimalNumber * average;

@property (nonatomic, readonly, nonnull) NSDecimalNumber * fast;

@property (nonatomic, readonly) float slowTime;

@property (nonatomic, readonly) float averageTime;

@property (nonatomic, readonly) float fastTime;

@property (nonatomic, readonly, nonnull) NSString * source;

@end
