// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from user.djinni

#import "ZKQuote.h"
#import <Foundation/Foundation.h>


/** Callback interface used by methods in `ZKUser` class. */
@protocol ZKQuoteCallback

- (void)onError:(nonnull NSError *)e;

- (void)onSuccess:(nonnull ZKQuote *)quote;

@end
