// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from records.djinni

#import <Foundation/Foundation.h>

/** Record containing Zumo exchange rate quote used in making exchanges. */
@interface ZKQuote : NSObject
- (nonnull instancetype)initWithId:(nonnull NSString *)id
                               ttl:(int32_t)ttl
                         createdAt:(nonnull NSString *)createdAt
                         expiresAt:(nonnull NSString *)expiresAt
                     debitCurrency:(nonnull NSString *)debitCurrency
                    creditCurrency:(nonnull NSString *)creditCurrency
                             price:(nonnull NSDecimalNumber *)price
                           feeRate:(nonnull NSDecimalNumber *)feeRate
                       debitAmount:(nonnull NSDecimalNumber *)debitAmount
                         feeAmount:(nonnull NSDecimalNumber *)feeAmount
                      creditAmount:(nonnull NSDecimalNumber *)creditAmount;
+ (nonnull instancetype)quoteWithId:(nonnull NSString *)id
                                ttl:(int32_t)ttl
                          createdAt:(nonnull NSString *)createdAt
                          expiresAt:(nonnull NSString *)expiresAt
                      debitCurrency:(nonnull NSString *)debitCurrency
                     creditCurrency:(nonnull NSString *)creditCurrency
                              price:(nonnull NSDecimalNumber *)price
                            feeRate:(nonnull NSDecimalNumber *)feeRate
                        debitAmount:(nonnull NSDecimalNumber *)debitAmount
                          feeAmount:(nonnull NSDecimalNumber *)feeAmount
                       creditAmount:(nonnull NSDecimalNumber *)creditAmount;

/** Identifier. */
@property (nonatomic, readonly, nonnull) NSString * id;

/** Expiration in seconds at the time of quote creation, e.g. 60. */
@property (nonatomic, readonly) int32_t ttl;

/** Timestamp when quote was created, e.g.  "2022-10-13T12:39:59.056Z". */
@property (nonatomic, readonly, nonnull) NSString * createdAt;

/** Timestamp representing expiration time of this quote, e.g. "2022-10-13T12:40:58.871Z". */
@property (nonatomic, readonly, nonnull) NSString * expiresAt;

/**
 * Debit currency.
 * @see `ZKCurrencyCode`
 */
@property (nonatomic, readonly, nonnull) NSString * debitCurrency;

/**
 * Credit currency.
 * @see `ZKCurrencyCode`
 */
@property (nonatomic, readonly, nonnull) NSString * creditCurrency;

/** Value of 1 unit of debit currency in credit currency. */
@property (nonatomic, readonly, nonnull) NSDecimalNumber * price;

/** Fee rate in points of a percentage, e.g. "0.1" representing 0.1% */
@property (nonatomic, readonly, nonnull) NSDecimalNumber * feeRate;

/** Amount to be debited from debit account. */
@property (nonatomic, readonly, nonnull) NSDecimalNumber * debitAmount;

/** Amount that will be paid in fees. */
@property (nonatomic, readonly, nonnull) NSDecimalNumber * feeAmount;

/** Amount to be credited to credit account. */
@property (nonatomic, readonly, nonnull) NSDecimalNumber * creditAmount;

@end
