// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from wallet.djinni

#import "ZKExchange.h"
#import <Foundation/Foundation.h>


/** Callback interface used by methods in `ZKWallet` class. */
@protocol ZKSubmitExchangeCallback

- (void)onError:(nonnull NSError *)e;

- (void)onSuccess:(nonnull ZKExchange *)exchage;

@end
