// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from records.djinni

#import "ZKTimeInterval.h"


NSString * __nonnull const ZKTimeIntervalHOUR = @"hour";

NSString * __nonnull const ZKTimeIntervalDAY = @"day";

NSString * __nonnull const ZKTimeIntervalWEEK = @"week";

NSString * __nonnull const ZKTimeIntervalMONTH = @"month";

NSString * __nonnull const ZKTimeIntervalQUARTER = @"quarter";

NSString * __nonnull const ZKTimeIntervalYEAR = @"year";

@implementation ZKTimeInterval

- (nonnull instancetype)init
{
    if (self = [super init]) {
    }
    return self;
}

+ (nonnull instancetype)timeInterval
{
    return [(ZKTimeInterval*)[self alloc] init];
}

- (NSString *)description
{
    return [NSString stringWithFormat:@"<%@ %p>", self.class, (void *)self];
}

@end
