// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from enums.djinni

#import <Foundation/Foundation.h>

/** Time intervals, such as 'hour', 'week' or 'year' */
@interface ZKTimeInterval : NSObject
- (nonnull instancetype)init;
+ (nonnull instancetype)timeInterval;

@end

extern NSString * __nonnull const ZKTimeIntervalHOUR;
extern NSString * __nonnull const ZKTimeIntervalDAY;
extern NSString * __nonnull const ZKTimeIntervalWEEK;
extern NSString * __nonnull const ZKTimeIntervalMONTH;
extern NSString * __nonnull const ZKTimeIntervalQUARTER;
extern NSString * __nonnull const ZKTimeIntervalYEAR;
