// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from state.djinni

#import "ZKNetworkType.h"
#import "ZKTransactionDirection.h"
#import "ZKTransactionStatus.h"
#import "ZKTransactionType.h"
#import <Foundation/Foundation.h>

@interface ZKTransaction : NSObject
- (nonnull instancetype)initWithId:(nonnull NSString *)id
                              type:(ZKTransactionType)type
                         direction:(ZKTransactionDirection)direction
                            txHash:(nullable NSString *)txHash
                         accountId:(nonnull NSString *)accountId
                            symbol:(nullable NSString *)symbol
                              coin:(nonnull NSString *)coin
                           network:(ZKNetworkType)network
                             nonce:(nullable NSNumber *)nonce
                            status:(ZKTransactionStatus)status
                       fromAddress:(nonnull NSString *)fromAddress
                        fromUserId:(nullable NSString *)fromUserId
                         toAddress:(nonnull NSString *)toAddress
                          toUserId:(nullable NSString *)toUserId
                             value:(nullable NSString *)value
                         fiatValue:(nonnull NSDictionary<NSString *, NSString *> *)fiatValue
                              data:(nullable NSString *)data
                          gasPrice:(nullable NSString *)gasPrice
                          gasLimit:(nullable NSString *)gasLimit
                               fee:(nullable NSString *)fee
                           fiatFee:(nonnull NSDictionary<NSString *, NSString *> *)fiatFee
                       submittedAt:(nullable NSNumber *)submittedAt
                       confirmedAt:(nullable NSNumber *)confirmedAt
                         timestamp:(int64_t)timestamp;
+ (nonnull instancetype)transactionWithId:(nonnull NSString *)id
                                     type:(ZKTransactionType)type
                                direction:(ZKTransactionDirection)direction
                                   txHash:(nullable NSString *)txHash
                                accountId:(nonnull NSString *)accountId
                                   symbol:(nullable NSString *)symbol
                                     coin:(nonnull NSString *)coin
                                  network:(ZKNetworkType)network
                                    nonce:(nullable NSNumber *)nonce
                                   status:(ZKTransactionStatus)status
                              fromAddress:(nonnull NSString *)fromAddress
                               fromUserId:(nullable NSString *)fromUserId
                                toAddress:(nonnull NSString *)toAddress
                                 toUserId:(nullable NSString *)toUserId
                                    value:(nullable NSString *)value
                                fiatValue:(nonnull NSDictionary<NSString *, NSString *> *)fiatValue
                                     data:(nullable NSString *)data
                                 gasPrice:(nullable NSString *)gasPrice
                                 gasLimit:(nullable NSString *)gasLimit
                                      fee:(nullable NSString *)fee
                                  fiatFee:(nonnull NSDictionary<NSString *, NSString *> *)fiatFee
                              submittedAt:(nullable NSNumber *)submittedAt
                              confirmedAt:(nullable NSNumber *)confirmedAt
                                timestamp:(int64_t)timestamp;

@property (nonatomic, readonly, nonnull) NSString * id;

@property (nonatomic, readonly) ZKTransactionType type;

@property (nonatomic, readonly) ZKTransactionDirection direction;

@property (nonatomic, readonly, nullable) NSString * txHash;

@property (nonatomic, readonly, nonnull) NSString * accountId;

@property (nonatomic, readonly, nullable) NSString * symbol;

@property (nonatomic, readonly, nonnull) NSString * coin;

@property (nonatomic, readonly) ZKNetworkType network;

@property (nonatomic, readonly, nullable) NSNumber * nonce;

@property (nonatomic, readonly) ZKTransactionStatus status;

@property (nonatomic, readonly, nonnull) NSString * fromAddress;

@property (nonatomic, readonly, nullable) NSString * fromUserId;

@property (nonatomic, readonly, nonnull) NSString * toAddress;

@property (nonatomic, readonly, nullable) NSString * toUserId;

@property (nonatomic, readonly, nullable) NSString * value;

@property (nonatomic, readonly, nonnull) NSDictionary<NSString *, NSString *> * fiatValue;

@property (nonatomic, readonly, nullable) NSString * data;

@property (nonatomic, readonly, nullable) NSString * gasPrice;

@property (nonatomic, readonly, nullable) NSString * gasLimit;

@property (nonatomic, readonly, nullable) NSString * fee;

@property (nonatomic, readonly, nonnull) NSDictionary<NSString *, NSString *> * fiatFee;

@property (nonatomic, readonly, nullable) NSNumber * submittedAt;

@property (nonatomic, readonly, nullable) NSNumber * confirmedAt;

@property (nonatomic, readonly) int64_t timestamp;

@end
