// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from state.djinni

#import "ZKTransactionDirection.h"


NSString * __nonnull const ZKTransactionDirectionINCOMING = @"INCOMING";

NSString * __nonnull const ZKTransactionDirectionOUTGOING = @"OUTGOING";

NSString * __nonnull const ZKTransactionDirectionFAILED = @"FAILED";

NSString * __nonnull const ZKTransactionDirectionRESUBMITTED = @"RESUBMITTED";

NSString * __nonnull const ZKTransactionDirectionCANCELLED = @"CANCELLED";

NSString * __nonnull const ZKTransactionDirectionPAUSED = @"PAUSED";

@implementation ZKTransactionDirection

- (nonnull instancetype)init
{
    if (self = [super init]) {
    }
    return self;
}

+ (nonnull instancetype)transactionDirection
{
    return [(ZKTransactionDirection*)[self alloc] init];
}

- (NSString *)description
{
    return [NSString stringWithFormat:@"<%@ %p>", self.class, (void *)self];
}

@end
