// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from records.djinni

#import <Foundation/Foundation.h>

/**
 * Record containing properties associated with a card transaction.
 * @see `ZKTransaction`
 */
@interface ZKTransactionCardProperties : NSObject
- (nonnull instancetype)initWithCardId:(nonnull NSString *)cardId
                     transactionAmount:(nonnull NSDecimalNumber *)transactionAmount
                   transactionCurrency:(nonnull NSString *)transactionCurrency
                         billingAmount:(nonnull NSDecimalNumber *)billingAmount
                       billingCurrency:(nonnull NSString *)billingCurrency
                     exchangeRateValue:(nonnull NSDecimalNumber *)exchangeRateValue
                                   mcc:(nonnull NSString *)mcc
                          merchantName:(nonnull NSString *)merchantName
                       merchantCountry:(nonnull NSString *)merchantCountry;
+ (nonnull instancetype)transactionCardPropertiesWithCardId:(nonnull NSString *)cardId
                                          transactionAmount:(nonnull NSDecimalNumber *)transactionAmount
                                        transactionCurrency:(nonnull NSString *)transactionCurrency
                                              billingAmount:(nonnull NSDecimalNumber *)billingAmount
                                            billingCurrency:(nonnull NSString *)billingCurrency
                                          exchangeRateValue:(nonnull NSDecimalNumber *)exchangeRateValue
                                                        mcc:(nonnull NSString *)mcc
                                               merchantName:(nonnull NSString *)merchantName
                                            merchantCountry:(nonnull NSString *)merchantCountry;

/**
 * Card identifier.
 * @see `ZKCard`
 */
@property (nonatomic, readonly, nonnull) NSString * cardId;

/** Transaction amount. */
@property (nonatomic, readonly, nonnull) NSDecimalNumber * transactionAmount;

/**
 * Transaction currency code.
 * @see `ZKCurrencyCode` 
 */
@property (nonatomic, readonly, nonnull) NSString * transactionCurrency;

/** Billing amount. */
@property (nonatomic, readonly, nonnull) NSDecimalNumber * billingAmount;

/**
 * Billing currency code.
 * @see `ZKCurrencyCode` 
 */
@property (nonatomic, readonly, nonnull) NSString * billingCurrency;

/** Exchange rate applied to any conversion between transaction & billing amount rounded to 6 decimal places. */
@property (nonatomic, readonly, nonnull) NSDecimalNumber * exchangeRateValue;

/** The Merchant Category Code (MCC) for the card activity in ISO-18245 format. */
@property (nonatomic, readonly, nonnull) NSString * mcc;

/** The merchant name. */
@property (nonatomic, readonly, nonnull) NSString * merchantName;

/** The 3 letter ISO 3166 merchant country code. */
@property (nonatomic, readonly, nonnull) NSString * merchantCountry;

@end
