// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from state.djinni

#import "ZKCryptoDetails.h"
#import <Foundation/Foundation.h>

@interface ZKTransaction : NSObject
- (nonnull instancetype)initWithId:(nonnull NSString *)id
                              type:(nonnull NSString *)type
                         accountId:(nonnull NSString *)accountId
                      currencyCode:(nonnull NSString *)currencyCode
                        fromUserId:(nullable NSString *)fromUserId
                          toUserId:(nullable NSString *)toUserId
                           network:(nonnull NSString *)network
                         direction:(nonnull NSString *)direction
                            status:(nonnull NSString *)status
                            amount:(nullable NSString *)amount
                               fee:(nullable NSString *)fee
                     cryptoDetails:(nullable ZKCryptoDetails *)cryptoDetails
                       fiatDetails:(nullable NSString *)fiatDetails
                       submittedAt:(nullable NSNumber *)submittedAt
                       confirmedAt:(nullable NSNumber *)confirmedAt
                         timestamp:(int64_t)timestamp;
+ (nonnull instancetype)transactionWithId:(nonnull NSString *)id
                                     type:(nonnull NSString *)type
                                accountId:(nonnull NSString *)accountId
                             currencyCode:(nonnull NSString *)currencyCode
                               fromUserId:(nullable NSString *)fromUserId
                                 toUserId:(nullable NSString *)toUserId
                                  network:(nonnull NSString *)network
                                direction:(nonnull NSString *)direction
                                   status:(nonnull NSString *)status
                                   amount:(nullable NSString *)amount
                                      fee:(nullable NSString *)fee
                            cryptoDetails:(nullable ZKCryptoDetails *)cryptoDetails
                              fiatDetails:(nullable NSString *)fiatDetails
                              submittedAt:(nullable NSNumber *)submittedAt
                              confirmedAt:(nullable NSNumber *)confirmedAt
                                timestamp:(int64_t)timestamp;

@property (nonatomic, readonly, nonnull) NSString * id;

@property (nonatomic, readonly, nonnull) NSString * type;

@property (nonatomic, readonly, nonnull) NSString * accountId;

@property (nonatomic, readonly, nonnull) NSString * currencyCode;

@property (nonatomic, readonly, nullable) NSString * fromUserId;

@property (nonatomic, readonly, nullable) NSString * toUserId;

@property (nonatomic, readonly, nonnull) NSString * network;

@property (nonatomic, readonly, nonnull) NSString * direction;

@property (nonatomic, readonly, nonnull) NSString * status;

@property (nonatomic, readonly, nullable) NSString * amount;

@property (nonatomic, readonly, nullable) NSString * fee;

@property (nonatomic, readonly, nullable) ZKCryptoDetails * cryptoDetails;

@property (nonatomic, readonly, nullable) NSString * fiatDetails;

@property (nonatomic, readonly, nullable) NSNumber * submittedAt;

@property (nonatomic, readonly, nullable) NSNumber * confirmedAt;

@property (nonatomic, readonly) int64_t timestamp;

@end
