// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from state.djinni

#import <Foundation/Foundation.h>

@interface ZKTransactionStatus : NSObject
- (nonnull instancetype)init;
+ (nonnull instancetype)transactionStatus;

@end

extern NSString * __nonnull const ZKTransactionStatusPENDING;
extern NSString * __nonnull const ZKTransactionStatusCONFIRMED;
extern NSString * __nonnull const ZKTransactionStatusFAILED;
extern NSString * __nonnull const ZKTransactionStatusRESUBMITTED;
extern NSString * __nonnull const ZKTransactionStatusCANCELLED;
extern NSString * __nonnull const ZKTransactionStatusPAUSED;
