// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from user.djinni

#import "ZKTransaction.h"
#import <Foundation/Foundation.h>


/** Callback interface used by methods in @link user class. */
@protocol ZKTransactionListener

- (void)update:(nullable ZKTransaction *)transaction;

@end
