// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from state.djinni

#import "ZKAccountFiatProperties.h"
#import <Foundation/Foundation.h>

@interface ZKTransactionFiatProperties : NSObject
- (nonnull instancetype)initWithFromFiatAccount:(nonnull ZKAccountFiatProperties *)fromFiatAccount
                                  toFiatAccount:(nonnull ZKAccountFiatProperties *)toFiatAccount;
+ (nonnull instancetype)transactionFiatPropertiesWithFromFiatAccount:(nonnull ZKAccountFiatProperties *)fromFiatAccount
                                                       toFiatAccount:(nonnull ZKAccountFiatProperties *)toFiatAccount;

@property (nonatomic, readonly, nonnull) ZKAccountFiatProperties * fromFiatAccount;

@property (nonatomic, readonly, nonnull) ZKAccountFiatProperties * toFiatAccount;

@end
