// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from state.djinni

#import "ZKTransactionFiatProperties.h"


@implementation ZKTransactionFiatProperties

- (nonnull instancetype)initWithFromFiatAccount:(nonnull ZKAccountFiatProperties *)fromFiatAccount
                                  toFiatAccount:(nonnull ZKAccountFiatProperties *)toFiatAccount
{
    if (self = [super init]) {
        _fromFiatAccount = fromFiatAccount;
        _toFiatAccount = toFiatAccount;
    }
    return self;
}

+ (nonnull instancetype)transactionFiatPropertiesWithFromFiatAccount:(nonnull ZKAccountFiatProperties *)fromFiatAccount
                                                       toFiatAccount:(nonnull ZKAccountFiatProperties *)toFiatAccount
{
    return [(ZKTransactionFiatProperties*)[self alloc] initWithFromFiatAccount:fromFiatAccount
                                                                 toFiatAccount:toFiatAccount];
}

- (BOOL)isEqual:(id)other
{
    if (![other isKindOfClass:[ZKTransactionFiatProperties class]]) {
        return NO;
    }
    ZKTransactionFiatProperties *typedOther = (ZKTransactionFiatProperties *)other;
    return [self.fromFiatAccount isEqual:typedOther.fromFiatAccount] &&
            [self.toFiatAccount isEqual:typedOther.toFiatAccount];
}

- (NSUInteger)hash
{
    return NSStringFromClass([self class]).hash ^
            self.fromFiatAccount.hash ^
            self.toFiatAccount.hash;
}

- (NSString *)description
{
    return [NSString stringWithFormat:@"<%@ %p fromFiatAccount:%@ toFiatAccount:%@>", self.class, (void *)self, self.fromFiatAccount, self.toFiatAccount];
}

@end
