// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from records.djinni

#import "ZKTransactionDirection.h"


NSString * __nonnull const ZKTransactionDirectionINCOMING = @"INCOMING";

NSString * __nonnull const ZKTransactionDirectionOUTGOING = @"OUTGOING";

@implementation ZKTransactionDirection

- (nonnull instancetype)init
{
    if (self = [super init]) {
    }
    return self;
}

+ (nonnull instancetype)transactionDirection
{
    return [(ZKTransactionDirection*)[self alloc] init];
}

- (NSString *)description
{
    return [NSString stringWithFormat:@"<%@ %p>", self.class, (void *)self];
}

@end
