// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from records.djinni

#import <Foundation/Foundation.h>

/** Record containing transaction amount details. */
@interface ZKTransactionAmount : NSObject
- (nonnull instancetype)initWithDirection:(nonnull NSString *)direction
                                   userId:(nullable NSString *)userId
                         userIntegratorId:(nullable NSString *)userIntegratorId
                                accountId:(nullable NSString *)accountId
                                   amount:(nullable NSDecimalNumber *)amount
                               fiatAmount:(nullable NSDictionary<NSString *, NSNumber *> *)fiatAmount
                                  address:(nullable NSString *)address
                                 isChange:(BOOL)isChange
                            accountNumber:(nullable NSString *)accountNumber
                                 sortCode:(nullable NSString *)sortCode
                                      bic:(nullable NSString *)bic
                                     iban:(nullable NSString *)iban;
+ (nonnull instancetype)transactionAmountWithDirection:(nonnull NSString *)direction
                                                userId:(nullable NSString *)userId
                                      userIntegratorId:(nullable NSString *)userIntegratorId
                                             accountId:(nullable NSString *)accountId
                                                amount:(nullable NSDecimalNumber *)amount
                                            fiatAmount:(nullable NSDictionary<NSString *, NSNumber *> *)fiatAmount
                                               address:(nullable NSString *)address
                                              isChange:(BOOL)isChange
                                         accountNumber:(nullable NSString *)accountNumber
                                              sortCode:(nullable NSString *)sortCode
                                                   bic:(nullable NSString *)bic
                                                  iban:(nullable NSString *)iban;

/**
 * Direction, either 'SENT' or 'RECEIVED'.
 * @see `ZKTransactionDirection`
 */
@property (nonatomic, readonly, nonnull) NSString * direction;

/** User id or null if it is external user. */
@property (nonatomic, readonly, nullable) NSString * userId;

/** User integrator id or null if it is external user. */
@property (nonatomic, readonly, nullable) NSString * userIntegratorId;

/** Account id or null if it is external user. */
@property (nonatomic, readonly, nullable) NSString * accountId;

/** Amount in transaction currency or null if transaction is Ethereum contract deploy. */
@property (nonatomic, readonly, nullable) NSDecimalNumber * amount;

/**
 * Amount in fiat currencies at the time of the transaction submission.
 * @see `ZKCurrencyCode`
 */
@property (nonatomic, readonly, nullable) NSDictionary<NSString *, NSNumber *> * fiatAmount;

/** Blockchain address or null.  */
@property (nonatomic, readonly, nullable) NSString * address;

/** Indicates if this amount represents change amount. */
@property (nonatomic, readonly) BOOL isChange;

/** Fiat account number or null. */
@property (nonatomic, readonly, nullable) NSString * accountNumber;

/** Fiat account sort code or null. */
@property (nonatomic, readonly, nullable) NSString * sortCode;

/** Fiat account BIC or null. */
@property (nonatomic, readonly, nullable) NSString * bic;

/** Fiat account IBAN or null. */
@property (nonatomic, readonly, nullable) NSString * iban;

@end
