// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from enums.djinni

#import <Foundation/Foundation.h>

/** Transaction type, 'CUSTODY', 'CUSTODY-DEPOSIT', 'CUSTODY-WITHDRAW', 'CRYPTO', 'FIAT', 'NOMINATED' or 'CARD'. */
@interface ZKTransactionType : NSObject
- (nonnull instancetype)init;
+ (nonnull instancetype)transactionType;

@end

extern NSString * __nonnull const ZKTransactionTypeCUSTODY;
extern NSString * __nonnull const ZKTransactionTypeCUSTODYDEPOSIT;
extern NSString * __nonnull const ZKTransactionTypeCUSTODYWITHDRAW;
extern NSString * __nonnull const ZKTransactionTypeCRYPTO;
extern NSString * __nonnull const ZKTransactionTypeFIAT;
extern NSString * __nonnull const ZKTransactionTypeNOMINATED;
extern NSString * __nonnull const ZKTransactionTypeCARD;
