// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from state.djinni

#import <Foundation/Foundation.h>

/** Transaction direction, 'INCOMING' or 'OUTGOING'. */
@interface ZKTransactionDirection : NSObject
- (nonnull instancetype)init;
+ (nonnull instancetype)transactionDirection;

@end

extern NSString * __nonnull const ZKTransactionDirectionINCOMING;
extern NSString * __nonnull const ZKTransactionDirectionOUTGOING;
