// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from state.djinni

#import "ZKTxServiceConnection.h"


@implementation ZKTxServiceConnection

- (nonnull instancetype)initWithStatus:(ZKConnectionStatus)status
                         lastConnected:(int64_t)lastConnected
{
    if (self = [super init]) {
        _status = status;
        _lastConnected = lastConnected;
    }
    return self;
}

+ (nonnull instancetype)txServiceConnectionWithStatus:(ZKConnectionStatus)status
                                        lastConnected:(int64_t)lastConnected
{
    return [(ZKTxServiceConnection*)[self alloc] initWithStatus:status
                                                  lastConnected:lastConnected];
}

- (BOOL)isEqual:(id)other
{
    if (![other isKindOfClass:[ZKTxServiceConnection class]]) {
        return NO;
    }
    ZKTxServiceConnection *typedOther = (ZKTxServiceConnection *)other;
    return self.status == typedOther.status &&
            self.lastConnected == typedOther.lastConnected;
}

- (NSUInteger)hash
{
    return NSStringFromClass([self class]).hash ^
            (NSUInteger)self.status ^
            (NSUInteger)self.lastConnected;
}

- (NSString *)description
{
    return [NSString stringWithFormat:@"<%@ %p status:%@ lastConnected:%@>", self.class, (void *)self, @(self.status), @(self.lastConnected)];
}

@end
