// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from utils.djinni

#import "ZKNetworkType.h"
#import <Foundation/Foundation.h>


@interface ZKUtils : NSObject

- (nonnull NSString *)generateMnemonic:(int32_t)wordCount;

- (BOOL)isValidEthAddress:(nonnull NSString *)address;

- (BOOL)isValidBtcAddress:(nonnull NSString *)address
                  network:(ZKNetworkType)network;

- (nonnull NSString *)weiToEth:(nonnull NSString *)number;

- (nonnull NSString *)ethToWei:(nonnull NSString *)number;

- (nonnull NSString *)gweiToEth:(nonnull NSString *)number;

- (nonnull NSString *)ethToGwei:(nonnull NSString *)number;

- (nonnull NSString *)weiToGwei:(nonnull NSString *)number;

- (nonnull NSString *)gweiToWei:(nonnull NSString *)number;

@end
