// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from errors.djinni

#import <Foundation/Foundation.h>

@interface ZKZumoKitErrorCode : NSObject
- (nonnull instancetype)init;
+ (nonnull instancetype)zumoKitErrorCode;

@end

extern NSString * __nonnull const ZKZumoKitErrorCodeUNKNOWNERROR;
extern NSString * __nonnull const ZKZumoKitErrorCodeINVALIDAPIRESPONSE;
extern NSString * __nonnull const ZKZumoKitErrorCodeINVALIDWEBSOCKETRESPONSE;
extern NSString * __nonnull const ZKZumoKitErrorCodeAPISERVICEERROR;
extern NSString * __nonnull const ZKZumoKitErrorCodeTRANSACTIONSERVICEERROR;
extern NSString * __nonnull const ZKZumoKitErrorCodeNOTAUTHORIZED;
extern NSString * __nonnull const ZKZumoKitErrorCodeWALLETLIMITEXCEEDED;
extern NSString * __nonnull const ZKZumoKitErrorCodeNOWALLETTORECOVERFOUND;
extern NSString * __nonnull const ZKZumoKitErrorCodeINVALIDRECOVERYPHRASE;
extern NSString * __nonnull const ZKZumoKitErrorCodeINVALIDMNEMONICWORDCOUNT;
extern NSString * __nonnull const ZKZumoKitErrorCodeINVALIDPASSWORD;
extern NSString * __nonnull const ZKZumoKitErrorCodeINVALIDNETWORKTYPE;
extern NSString * __nonnull const ZKZumoKitErrorCodeBITCOINAMOUNTOVERFLOW;
extern NSString * __nonnull const ZKZumoKitErrorCodeSIGNINGERROR;
extern NSString * __nonnull const ZKZumoKitErrorCodeUTXOSIGNINGERROR;
extern NSString * __nonnull const ZKZumoKitErrorCodeINVALIDHDWALLETPATH;
extern NSString * __nonnull const ZKZumoKitErrorCodeCHANGEACCOUNTNOTFOUND;
extern NSString * __nonnull const ZKZumoKitErrorCodeACCOUNTNOTFOUND;
extern NSString * __nonnull const ZKZumoKitErrorCodeKNOWNTRANSACTION;
extern NSString * __nonnull const ZKZumoKitErrorCodeINVALIDTRANSACTIONVALUE;
extern NSString * __nonnull const ZKZumoKitErrorCodeINVALIDFEERATE;
extern NSString * __nonnull const ZKZumoKitErrorCodeINVALIDADDRESS;
extern NSString * __nonnull const ZKZumoKitErrorCodeINSUFFICIENTFUNDS;
extern NSString * __nonnull const ZKZumoKitErrorCodeINSUFFICIENTFUNDSFORTRANSACTION;
extern NSString * __nonnull const ZKZumoKitErrorCodeINSUFFICIENTFUNDSFOREXCHANGE;
extern NSString * __nonnull const ZKZumoKitErrorCodeNONCEOVERFLOW;
extern NSString * __nonnull const ZKZumoKitErrorCodeGASTOOLOW;
extern NSString * __nonnull const ZKZumoKitErrorCodeGASOVERFLOW;
extern NSString * __nonnull const ZKZumoKitErrorCodeNODESTINATIONADDRESS;
extern NSString * __nonnull const ZKZumoKitErrorCodeDATAOVERFLOW;
extern NSString * __nonnull const ZKZumoKitErrorCodeINCOMPATIBLENETWORKTYPES;
extern NSString * __nonnull const ZKZumoKitErrorCodeINVALIDACCOUNTTYPE;
extern NSString * __nonnull const ZKZumoKitErrorCodeINVALIDEXCHANGERATE;
extern NSString * __nonnull const ZKZumoKitErrorCodeINVALIDEXCHANGESETTINGS;
extern NSString * __nonnull const ZKZumoKitErrorCodeEXCHANGERETURNVALUENEGATIVE;
extern NSString * __nonnull const ZKZumoKitErrorCodeINVALIDEXCHANGEDEPOSITADDRESS;
extern NSString * __nonnull const ZKZumoKitErrorCodeEXCHANGEAMOUNTTOOLOW;
extern NSString * __nonnull const ZKZumoKitErrorCodeVALUEPROVIDEDWHENSENDMAXSET;
extern NSString * __nonnull const ZKZumoKitErrorCodeDATAPROVIDEDWHENSENDMAXSET;
extern NSString * __nonnull const ZKZumoKitErrorCodeTRANSACTIONTOOLARGE;
extern NSString * __nonnull const ZKZumoKitErrorCodeCHANGEINDEXOUTOFRANGE;
extern NSString * __nonnull const ZKZumoKitErrorCodeTRANSACTIONAMOUNTTOOSMALL;
extern NSString * __nonnull const ZKZumoKitErrorCodeSENDMAXINSUFFICIENTFUNDSFORFEE;
extern NSString * __nonnull const ZKZumoKitErrorCodeSENDMAXINSUFFICIENTFUNDSFORTRANSACTION;
extern NSString * __nonnull const ZKZumoKitErrorCodeAMOUNTNOTSET;
extern NSString * __nonnull const ZKZumoKitErrorCodeALREADYMODULRCUSTOMER;
extern NSString * __nonnull const ZKZumoKitErrorCodeUSERNOTMODULRCUSTOMER;
extern NSString * __nonnull const ZKZumoKitErrorCodeACCOUNTLIMITEXCEEDED;
extern NSString * __nonnull const ZKZumoKitErrorCodeDESTINATIONPROVIDEDWHENWITHDRAWSET;
extern NSString * __nonnull const ZKZumoKitErrorCodeINVALIDTRANSACTIONTYPE;
