// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from errors.djinni

#import <Foundation/Foundation.h>

@interface ZKZumoKitError : NSObject
- (nonnull instancetype)initWithType:(nonnull NSString *)type
                                code:(nullable NSString *)code
                             message:(nullable NSString *)message;
+ (nonnull instancetype)zumoKitErrorWithType:(nonnull NSString *)type
                                        code:(nullable NSString *)code
                                     message:(nullable NSString *)message;

@property (nonatomic, readonly, nonnull) NSString * type;

@property (nonatomic, readonly, nullable) NSString * code;

@property (nonatomic, readonly, nullable) NSString * message;

@end

extern NSString * __nonnull const ZKZumoKitErrorAPICONNECTIONERROR;
extern NSString * __nonnull const ZKZumoKitErrorAPIERROR;
extern NSString * __nonnull const ZKZumoKitErrorAUTHENTICATIONERROR;
extern NSString * __nonnull const ZKZumoKitErrorWALLETERROR;
extern NSString * __nonnull const ZKZumoKitErrorTRANSACTIONERROR;
extern NSString * __nonnull const ZKZumoKitErrorINVALIDREQUESTERROR;
extern NSString * __nonnull const ZKZumoKitErrorRATELIMITERROR;
extern NSString * __nonnull const ZKZumoKitErrorINVALIDARGUMENTERROR;
