// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from errors.djinni

#import <Foundation/Foundation.h>

@interface ZKZumoKitErrorCode : NSObject
- (nonnull instancetype)init;
+ (nonnull instancetype)zumoKitErrorCode;

@end

extern NSString * __nonnull const ZKZumoKitErrorCodeNOTAUTHORIZED;
extern NSString * __nonnull const ZKZumoKitErrorCodeWALLETLIMITEXCEEDED;
extern NSString * __nonnull const ZKZumoKitErrorCodeNOWALLETTORECOVERFOUND;
extern NSString * __nonnull const ZKZumoKitErrorCodeINVALIDRECOVERYMNEMONIC;
extern NSString * __nonnull const ZKZumoKitErrorCodeINVALIDMNEMONICWORDCOUNT;
extern NSString * __nonnull const ZKZumoKitErrorCodeINVALIDPASSWORD;
extern NSString * __nonnull const ZKZumoKitErrorCodeINVALIDNETWORKTYPE;
extern NSString * __nonnull const ZKZumoKitErrorCodeBITCOINOVERFLOW;
extern NSString * __nonnull const ZKZumoKitErrorCodeSIGNINGERROR;
extern NSString * __nonnull const ZKZumoKitErrorCodeUTXOSIGNINGERROR;
extern NSString * __nonnull const ZKZumoKitErrorCodeINVALIDHDWALLETPATH;
extern NSString * __nonnull const ZKZumoKitErrorCodeCHANGEACCOUNTDOESNOTEXIST;
extern NSString * __nonnull const ZKZumoKitErrorCodeACCOUNTDOESNOTEXIST;
extern NSString * __nonnull const ZKZumoKitErrorCodeKNOWNTRANSACTION;
extern NSString * __nonnull const ZKZumoKitErrorCodeINVALIDTRANSACTIONVALUE;
extern NSString * __nonnull const ZKZumoKitErrorCodeINVALIDFEERATE;
extern NSString * __nonnull const ZKZumoKitErrorCodeINVALIDADDRESS;
extern NSString * __nonnull const ZKZumoKitErrorCodeINSUFFICIENTFUNDS;
